//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from hybrid_mp2.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: 90e4a6b2bfb596f42f0505903720c897

/// @file
/// The hybrid_mp2 stage module: the handshake, and one entry point per stage.

#include <Einsums/Python/StageModule.hpp>

#include <hybrid_mp2/Mp2Energy.hpp>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

PYBIND11_MODULE(hybrid_mp2_stages, m) {
    m.doc() = "C++ backends for the hybrid_mp2 stages.";

    // Must come first: einsums.stages.load_stage_module refuses to read
    // anything out of a module that has not registered against the same
    // libEinsums it is bound to.
    EINSUMS_STAGE_MODULE(m, "hybrid_mp2_stages");

    // Returned contracts are real bound types. Argument-position contracts
    // cross through the casters in Casters.hpp instead, which is why they need
    // no class_ here: direction decides the mechanism.
    // Every access to a list-valued field converts the underlying
    // std::vector into a fresh Python list. A consumer that indexes
    // result.field[i] inside a loop is therefore quadratic in the list
    // length; read each field into a local once and index that.
    py::class_<hybrid_mp2::Mp2Energy>(m, "Mp2Energy")
        .def_readonly("e_corr", &hybrid_mp2::Mp2Energy::e_corr)
        .def_readonly("e_os", &hybrid_mp2::Mp2Energy::e_os);

    // The stage_ prefix is what load_stage_module scans for: the module states
    // which of its symbols are stages rather than leaving the loader to guess
    // from everything callable.
    m.def("stage_mp2_energy", &hybrid_mp2::mp2_energy, py::arg("iajb"), py::arg("eps_occ"), py::arg("eps_vir"),
          "RHF MP2 correlation energy from MO `(ia|jb)` integrals.");
}
