//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

#pragma once

/**
 * @file TensorExpr.hpp
 * @brief A small algebraic IR over a graph region, and the raise / rewrite / lower loop.
 *
 * @par Why an expression IR and not more node surgery
 * `LinearCombinationContractionFolding` needed three graph-rewrite gotchas worked
 * around to fold a two-node transpose pattern; `ContractionPlanning` restructures
 * GEMM chains but works directly on nodes and stays narrow for the same reason.
 * The rewrites this module is heading for - dissolving user-chosen intermediates,
 * re-associating across many nodes, introducing tensors the user never wrote -
 * are not tractable to keep correct as node-level edits against live-mutable
 * shared descriptor state. So the framework is raise, rewrite, lower.
 *
 * @par The shape: a flat arena, not a pointer tree
 * @ref TensorExpr owns a vector of @ref ExprTerm and terms name their children by
 * INDEX. Three reasons, in order of weight:
 *
 *  - Leaves may be region-internal temporaries, so the algebra is a DAG rather
 *    than a tree the moment one intermediate feeds two consumers, and a tree of
 *    owning pointers would have to copy it.
 *  - Positional ids are what @ref GraphIR already uses to make two captures of
 *    one program produce byte-identical files, and a region dump is that same
 *    encoding with a different boundary rather than a second one to keep in step.
 *  - Nothing here iterates an unordered container, so a rewrite driven off this
 *    IR picks the same candidate on every run. The Kahn FIFO bug is the standing
 *    reminder that "some valid order" and "the same valid order every time" are
 *    different requirements.
 *
 * @par What is algebraic and what is carried
 * @ref TermKind::Contraction is fully algebraic: its per-operand index lists,
 * prefactors and conjugation flags are the rewrite surface, and lowering builds a
 * contraction node from them rather than from anything it remembered. That is
 * what `DeltaElimination` rewrites and what a factorization pass will
 * re-associate.
 *
 * @ref TermKind::Elementwise is NAMED and carries its descriptor. An algebraic
 * pass may delete it, reorder it or move it across a region boundary, but it does
 * not reach inside the kernel. Naming is a constraint rather than a convenience:
 * the same raise/lower machinery is what a gradient graph would be generated by,
 * and an opaque elementwise op is not differentiable by table while a named one
 * is.
 *
 * @par Lowering always rebuilds
 * @ref lower_region never reuses a node it raised. It could - every statement
 * records the node it came from - and that would make the identity test assert
 * nothing except that a vector round-trips. Rebuilding from the
 * algebra is what makes "raise everything, rewrite nothing, lower, get bitwise
 * identical results" a statement about the IR being faithful.
 *
 * Nodes are rebuilt through @ref build_executor, the one lowering point that
 * capture and @ref load_graph already share, so a generated node
 * is indistinguishable from a captured one and resolves its operands through the
 * graph's slots exactly as both of those do.
 *
 * @see EscapeAnalysis.hpp for the rule deciding what a region may dissolve
 * @see GraphIR.hpp for the round-trip encoding this IR deliberately resembles
 */

#include <Einsums/Config.hpp>

#include <Einsums/ComputeGraph/EscapeAnalysis.hpp>
#include <Einsums/ComputeGraph/Node.hpp>
#include <Einsums/ComputeGraph/SymbolicCost.hpp>
#include <Einsums/ComputeGraphTypes/Enums.hpp>
#include <Einsums/ComputeGraphTypes/Ids.hpp>
#include <Einsums/ComputeGraphTypes/Spaces.hpp>
#include <Einsums/Config/Namespace.hpp>

#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

EINSUMS_NAMESPACE_BEGIN(compute_graph)

class Graph;

/// @brief Index into @ref TensorExpr::terms. Positional and dense, like the IR's tensor ids.
using TermId = std::uint32_t;

/// @brief The term id no term has, for an empty slot.
inline constexpr TermId invalid_term = static_cast<TermId>(-1);

/**
 * @brief One index of a term, with the space it ranges over.
 *
 * The space may be invalid, which means the slot this letter met carried no
 * annotation. That is not an error and must not be treated as one: a partially
 * annotated program yields partial spaces rather than no expression, exactly as
 * @ref SymbolicVar's anonymous flavour yields a weaker comparison rather than no
 * comparison.
 */
struct ExprIndex {
    std::string letter; ///< The index letter, used verbatim including a multi-character name.
    SpaceId     space;  ///< The space this letter ranges over here, or an invalid id.

    friend bool operator==(ExprIndex const &lhs, ExprIndex const &rhs) = default;
};

/// @brief What an @ref ExprTerm computes.
enum class TermKind : std::uint8_t {
    /// A named tensor: a manifest entry, a user tensor, or a region-internal temporary.
    Leaf,
    /// A contraction of its operands over shared letters. Fully algebraic.
    Contraction,
    /// A named element-wise kernel over its operands. Named, not opaque; see the file note.
    Elementwise,
    /// A scalar multiple of its single operand.
    Scale,
    /// A sum of its operands, which must agree on free indices.
    Sum,
};

/// @brief Lower-case name of a term kind, for dumps and test tables.
/// @param[in] kind The kind to name.
/// @return One of ``leaf``, ``contraction``, ``elementwise``, ``scale``, ``sum``.
[[nodiscard]] EINSUMS_EXPORT std::string_view term_kind_name(TermKind kind);

/**
 * @brief One node of the expression arena.
 *
 * A struct with per-kind fields rather than a variant, because the arena is
 * serialized field-by-field into the round-trip encoding, and a variant would put
 * an alternative index between the writer and the names it is supposed to write.
 * Fields not belonging to a term's kind hold their defaults.
 */
struct ExprTerm {
    TermKind kind{TermKind::Leaf};

    /// Free indices of the value this term produces, in output order.
    std::vector<ExprIndex> indices;

    /// Children, by arena index. Empty for @ref TermKind::Leaf.
    std::vector<TermId> operands;

    /// @ref TermKind::Leaf: the tensor's name. @ref TermKind::Elementwise: the
    /// registered kernel's name. Empty otherwise.
    std::string name;

    /// @ref TermKind::Leaf: the graph tensor this leaf denotes.
    TensorId tensor{};

    /// @ref TermKind::Scale: the factor. @ref TermKind::Contraction: the product
    /// prefactor on the operands.
    PrefactorScalar factor{double{1}};

    /// @ref TermKind::Contraction: one index list per operand, in operand order.
    std::vector<std::vector<ExprIndex>> operand_indices;

    /// @ref TermKind::Contraction: whether to conjugate each operand.
    std::vector<bool> conjugate;

    /// @ref TermKind::Elementwise: the op kind whose descriptor @ref descriptor holds.
    OpKind element_kind{OpKind::Custom};

    /// @ref TermKind::Elementwise: the node descriptor, carried rather than
    /// interpreted. See the file note on why elementwise stays named.
    OpData descriptor;

    /// What this term costs, as a polynomial in space scales. Populated for
    /// @ref TermKind::Contraction, where the cost model has something to say;
    /// default (empty, meaning "nothing claimed") for the other kinds, because a
    /// zero cost and an unknown cost are different and only one of them is true.
    SymbolicCost cost;
};

/**
 * @brief One assignment of the raised region: a target, and the value put in it.
 *
 * A region raises to a SEQUENCE of these rather than to one expression, because a
 * region has as many outputs as its escape analysis says it does and because a
 * temporary the rewrite chooses not to dissolve has to stay a statement.
 */
struct ExprStatement {
    /// Where the value lands.
    TensorId target{};

    /// The target's name, for dumps.
    std::string target_name;

    /// The target's free indices.
    std::vector<ExprIndex> target_indices;

    /// The destination prefactor: zero overwrites, anything else accumulates.
    /// Carried algebraically because it is semantics, not an implementation
    /// detail: a rewrite that turned an accumulation into an overwrite would
    /// silently drop whatever else wrote the target.
    PrefactorScalar target_prefactor{double{0}};

    /// The value, by arena index.
    TermId value{invalid_term};

    /// The node this statement was raised from. Diagnostics only; lowering does
    /// NOT consult it, see the file note.
    NodeId origin{0};

    /// The node's kind at raise time, for reports that want to say what the
    /// algebra used to be.
    OpKind origin_kind{OpKind::Custom};

    /// The origin node's label, carried through a lowering so a report reads the
    /// same before and after an identity round-trip. A label names the arithmetic
    /// for a person and is not part of it, so carrying one is not the node reuse
    /// the file note rules out; a pass that genuinely changes what a statement
    /// computes should set its own.
    std::string origin_label;
};

/**
 * @brief The raised algebra of one region.
 *
 * @see raise_region, lower_region
 */
class EINSUMS_EXPORT TensorExpr {
  public:
    /// @brief The term arena. Children are named by index into this.
    std::vector<ExprTerm> terms;

    /// @brief The statements, in dependency order.
    std::vector<ExprStatement> statements;

    /**
     * @brief Append a term and return its id.
     * @param[in] term The term to append.
     * @return Its arena index.
     */
    TermId add(ExprTerm term);

    /// @brief The term at @p id.
    /// @param[in] id The arena index.
    /// @return The term.
    [[nodiscard]] ExprTerm const &at(TermId id) const { return terms.at(id); }

    /// @brief Mutable access to the term at @p id.
    /// @param[in] id The arena index.
    /// @return The term.
    [[nodiscard]] ExprTerm &at(TermId id) { return terms.at(id); }

    /**
     * @brief A one-line-per-statement rendering, for a report or a test.
     *
     * Reads as algebra rather than as a node list: ``C[i,j] += 2 * A[i,k] B[k,j]``.
     * A diffable before-and-after of THIS is a far better bug report than a
     * diff of two node dumps, which is the whole argument for dumping at all.
     *
     * @param[in] registry Space registry to name spaces through, or nullptr to
     *                     print letters alone.
     * @return The rendering, one statement per line, newline-terminated.
     */
    [[nodiscard]] std::string to_string(SpaceRegistry const *registry = nullptr) const;

    /// @brief Total symbolic cost of every contraction in the expression.
    /// @return The summed cost.
    [[nodiscard]] SymbolicCost total_cost() const;
};

/**
 * @brief A contiguous run of raisable nodes, and what crosses its boundary.
 *
 * @par Why contiguous
 * A region's replacement is spliced over its nodes, so a region whose nodes are
 * interleaved with nodes it does not contain would have to prove that splicing
 * at one position preserves every dependency the interleaved nodes have. That
 * proof is exactly the reasoning the program-order guard in `PassManager::run`
 * exists because passes got wrong (GEMMBatching appended a writer past a
 * surviving reader; LCCF was bitten by the same trap earlier). A maximal run of
 * CONSECUTIVE raisable nodes needs no such proof, and it is deliberately the
 * first cut: growing to non-contiguous regions is a later extension that has to
 * bring the reasoning with it.
 *
 * @par Barriers
 * Anything not in the raisable set ends a run: LAPACK, control flow,
 * communication, I/O, lifecycle, and an anonymous @ref OpKind::ElementTransform
 * whose kernel has no registered name. A method whose body is not flat therefore
 * gets a declined rewrite naming the barrier rather than a silently smaller
 * region.
 */
struct Region {
    /// Positions in ``graph.nodes()``, contiguous and ascending.
    std::size_t first{0};
    std::size_t last{0}; ///< One past the end.

    /// The node ids, in program order.
    std::vector<NodeId> nodes;

    /// Read inside, produced outside. Operands of the rewritten region.
    std::vector<TensorId> inputs;

    /// Written inside and observable outside. Must still be produced, and for a
    /// bitwise-exact rewrite must be produced bit-compatibly.
    std::vector<TensorId> outputs;

    /// Written and read only inside, and dissolvable: a rewrite may make these
    /// disappear entirely.
    std::vector<TensorId> internal;

    /// @brief How many nodes the region holds.
    /// @return The count.
    [[nodiscard]] std::size_t size() const { return nodes.size(); }
};

/**
 * @brief Whether a node kind can be raised into the algebra.
 *
 * Everything outside this set is a barrier, which is a
 * statement about what the IR can faithfully represent rather than about what is
 * interesting: a kind that raises has to lower back to the same arithmetic, and
 * a kind whose descriptor the IR cannot rebuild would round-trip into something
 * else.
 *
 * @param[in] kind The op kind.
 * @return True when a node of this kind may join a region.
 */
[[nodiscard]] EINSUMS_EXPORT bool is_raisable(OpKind kind);

/// @brief Knobs for @ref form_regions.
struct RegionOptions {
    /// Regions smaller than this are not formed. One-node regions are legal and
    /// useful for the identity test, which wants to raise everything; a rewriting
    /// pass usually wants at least two nodes before there is anything to say.
    std::size_t min_nodes{1};
};

/**
 * @brief Find every region of @p graph, deterministically.
 *
 * Runs are found by scanning nodes in program order, so the region set is the
 * same on every run over the same graph. A region set that varied between runs
 * would make every downstream rewrite vary with it.
 *
 * @param[in] graph   The graph to scan. Sub-graphs are not descended into.
 * @param[in] escapes The analysis over @p graph, used to classify each region's tensors.
 * @param[in] options Size gate; see @ref RegionOptions.
 * @return The regions, in program order.
 */
[[nodiscard]] EINSUMS_EXPORT std::vector<Region> form_regions(Graph const &graph, EscapeAnalysis const &escapes,
                                                              RegionOptions const &options = {});

/// @brief Why a region could not be raised.
struct RaiseFailure {
    /// Short and shape-independent, so @c note_skip aggregates it into one counted line.
    std::string reason;
    /// The specifics, for verbosity 3.
    std::string detail;
};

/**
 * @brief Raise @p region of @p graph into its algebra.
 *
 * @param[in] graph  The graph the region belongs to.
 * @param[in] region The region, as @ref form_regions produced it.
 * @return The expression, or the reason it could not be raised.
 *
 * Declines rather than approximating. A node whose descriptor does not carry
 * what the algebra needs - a contraction with no index lists, an elementwise op
 * with no registered name - fails the whole region, because a region raised with
 * one node silently dropped would lower into arithmetic that is missing a term.
 */
[[nodiscard]] EINSUMS_EXPORT expected<TensorExpr, RaiseFailure> raise_region(Graph const &graph, Region const &region);

/**
 * @brief Rebuild @p region of @p graph from @p expr, in place.
 *
 * The region's nodes are erased and the expression's statements are emitted at
 * the region's first position, so program order is preserved by construction and
 * no writer can end up behind a surviving reader.
 *
 * Every node is built from the algebra through @ref build_executor, the one
 * lowering point capture and @ref load_graph share. Nothing is reused from the
 * nodes that were raised; see the file note on why that is the point rather than
 * an inefficiency.
 *
 * @param[in,out] graph  The graph to rewrite.
 * @param[in]     region The region being replaced.
 * @param[in]     expr   The algebra to emit.
 * @return Nothing, or the reason the expression could not be lowered, in which
 *         case @p graph is left exactly as it was.
 */
[[nodiscard]] EINSUMS_EXPORT expected<void, RaiseFailure> lower_region(Graph &graph, Region const &region, TensorExpr const &expr);

EINSUMS_NAMESPACE_END(compute_graph)
