# ----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# ----------------------------------------------------------------------------------------------

# Stub overlay for the NumPy-style ergonomics that ``einsums/__init__.py``
# installs at RUNTIME (monkey-patched onto the bound RuntimeTensor classes +
# module-level constructors). The C++ codegen reads the AST and can't see runtime
# patching, so these stubs are maintained here and merged in by apiary's
# aggregate_stubs pass (see Einsums_FinalizePybind.cmake: STUB_OVERLAY /
# STUB_OVERLAY_CLASS_REGEX).
#
# Two parts:
#   * top-level ``def``s        -> module functions appended to einsums/__init__.pyi
#   * the class methods below    -> injected into every RuntimeTensor{F,D,C,Z} /
#                                   RuntimeTensorView{F,D,C,Z} class in _core.pyi
#
# Keep in sync with ``_patch_numpy_ergonomics`` and the constructors in
# ``einsums/__init__.py``. Imports here are for readability only; the aggregator
# ignores them (the generated stubs carry their own shared header).
from __future__ import annotations

from typing import Any

import numpy

def zeros(shape: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def ones(shape: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def empty(shape: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def full(shape: Any, fill_value: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def eye(n: int, m: Any = ..., dtype: Any = ..., name: Any = ...) -> Any: ...
def array(obj: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def asarray(obj: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def zeros_like(t: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def ones_like(t: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def empty_like(t: Any, dtype: Any = ..., name: Any = ...) -> Any: ...
def full_like(t: Any, fill_value: Any, dtype: Any = ..., name: Any = ...) -> Any: ...

class _TensorErgonomics:
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def dtype(self) -> numpy.dtype[Any]: ...
    @property
    def T(self) -> Any: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __array__(self, dtype: Any = ..., copy: Any = ...) -> numpy.ndarray[Any, Any]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def transpose(self, *axes: Any) -> Any: ...
    def swapaxes(self, axis1: int, axis2: int) -> Any: ...
    def copy(self) -> Any: ...
    def conj(self) -> Any: ...
    def adjoint(self) -> Any: ...
    @property
    def real(self) -> Any: ...
    @property
    def imag(self) -> Any: ...
    @property
    def H(self) -> Any: ...
    def __abs__(self) -> Any: ...
    def sum(self) -> Any: ...
    def mean(self) -> Any: ...
    def max(self) -> Any: ...
    def __matmul__(self, other: Any) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    def __pos__(self) -> Any: ...
    def __iadd__(self, other: Any) -> Any: ...
    def __isub__(self, other: Any) -> Any: ...
    def __imul__(self, other: Any) -> Any: ...
    def __itruediv__(self, other: Any) -> Any: ...
