//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// einsums._core entry point: runtime startup/shutdown and the PYBIND11_MODULE block. The per-module
// register functions come from a header einsums_finalize_pybind generates at configure time.

#include <Einsums/Config/ABI.hpp>
#include <Einsums/Options/Get.hpp>
#include <Einsums/Options/Parse.hpp>
#include <Einsums/Runtime/InitRuntime.hpp>
#include <Einsums/Runtime/Runtime.hpp>
#include <Einsums/Utilities/SetEnv.hpp>

#include <cstdint>
#include <cstdlib>
#include <pybind11/pybind11.h>
#include <pybind11/pytypes.h>
#include <pybind11/stl.h> // std::vector<std::string> caster for the cli_options argument
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

// Generated: apiary_register_<Module>() for each enabled module, and apiary_register_all().
#include <Einsums/Python/Detail/PyEinsumsModules.hpp>

namespace py = pybind11;

namespace {

// An option's rc attribute name: drop ``einsums:``, then map ``:`` and ``-`` to ``_``
// (``einsums:profile:report`` is ``profile_report``). rc.py is generated by the same rule.
std::string rc_attribute_name(std::string_view long_name) {
    constexpr std::string_view prefix = "einsums:";

    std::string_view rest = long_name;
    if (rest.starts_with(prefix)) {
        rest.remove_prefix(prefix.size());
    }

    std::string out(rest);
    for (char &c : out) {
        if (c == ':' || c == '-') {
            c = '_';
        }
    }
    return out;
}

// An integer setting, whether it was written as a plain int or as one of
// rc.py's enums (``LogLevel.INFO``). An Enum member carries the number in
// ``.value``; a plain int has no such attribute.
std::int64_t rc_int_value(py::object const &v) {
    py::object const n = py::hasattr(v, "value") ? v.attr("value") : v;
    return n.cast<std::int64_t>();
}

// rc.py's annotated fields are exactly the options plus ``threads``, so a field the registry does
// not claim names an option that no longer exists: refuse it loudly.
void reject_unknown_rc_fields(py::module_ const &rc, std::set<std::string> const &claimed) {
    if (!py::hasattr(rc, "__annotations__")) {
        return;
    }
    py::dict const annotations = rc.attr("__annotations__");

    std::string orphans;
    for (auto const item : annotations) {
        auto const name = item.first.cast<std::string>();
        // ``threads`` is not an option: it has no flag and routes through
        // OMP_NUM_THREADS, see apply_threads_from_rc.
        if (name == "threads" || name.starts_with("_") || claimed.contains(name)) {
            continue;
        }
        if (!orphans.empty()) {
            orphans += ", ";
        }
        orphans += name;
    }

    if (!orphans.empty()) {
        throw std::runtime_error("einsums.rc declares field(s) no registered option claims: " + orphans +
                                 ". rc.py is generated from the option descriptors; regenerate it "
                                 "(build the PyEinsums target) or remove the stale field.");
    }
}

// Translate einsums.rc settings into argv for einsums::initialize by walking the option registry,
// so a new option reaches Python with no table to edit.
std::vector<std::string> argv_from_rc(py::module_ const &rc) {
    std::vector<std::string> argv;
    argv.emplace_back("einsums-python");

    std::set<std::string> claimed;

    for (auto const &opt : einsums::cl::registered_options()) {
        std::string const attr = rc_attribute_name(opt.name);
        claimed.insert(attr);

        if (!py::hasattr(rc, attr.c_str())) {
            continue;
        }
        py::object const v = rc.attr(attr.c_str());
        // ``None`` is "leave the runtime default alone", which is what an
        // absent flag means, so nothing is emitted.
        if (v.is_none()) {
            continue;
        }

        // ``False`` is expressed with the flag's negated spelling.
        if (opt.kind == einsums::cl::OptionKind::Flag) {
            argv.emplace_back("--" + (v.cast<bool>() ? opt.name : opt.negated_name));
            continue;
        }

        std::string rendered;
        switch (opt.type) {
        case einsums::cl::OptionType::String:
            rendered = v.cast<std::string>();
            break;
        case einsums::cl::OptionType::Int:
            rendered = std::to_string(rc_int_value(v));
            break;
        case einsums::cl::OptionType::Double:
            rendered = std::to_string(v.cast<double>());
            break;
        case einsums::cl::OptionType::Bool:
            rendered = v.cast<bool>() ? "true" : "false";
            break;
        }
        // ``--name=value`` keeps a value with spaces in one argv element.
        argv.emplace_back("--" + opt.name + "=" + rendered);
    }

    reject_unknown_rc_fields(rc, claimed);

    return argv;
}

// rc.threads has no flag: it sets OMP_NUM_THREADS before initialize() starts any workers.
void apply_threads_from_rc(py::module_ const &rc) {
    py::object const v = rc.attr("threads");
    if (v.is(py::none())) {
        return;
    }
    int const n = v.cast<int>();
    einsums::set_env_var("OMP_NUM_THREADS", std::to_string(n));
}

// Py_AtExit hook, run after module destruction with the GIL dropped: no py:: state here.
extern "C" void einsums_python_atexit() {
    if (einsums::is_running()) {
        einsums::finalize();
    }
}

} // namespace

PYBIND11_MODULE(_core, m) {
    m.doc() = "Einsums Python bindings (autogenerated; see einsums_finalize_pybind).";

    // Importing _core only registers bindings. The runtime starts lazily, through _initialize_from_rc
    // on first real use (einsums/__init__.py::_ensure_initialized), after einsums.rc is configured.
    m.def(
        "_initialize_from_rc",
        [](std::vector<std::string> const &cli_options) {
            // Idempotent. einsums.rc is pure Python, so importing it does not recurse into _core.
            if (einsums::is_running()) {
                return;
            }
            py::module_ const rc = py::module_::import("einsums.rc");
            apply_threads_from_rc(rc);                        // OMP_NUM_THREADS env var
            std::vector<std::string> argv = argv_from_rc(rc); // CLI flags
            // Command-line ``--einsums:*`` flags (einsums.cli_options) go last, so they override rc.
            argv.insert(argv.end(), cli_options.begin(), cli_options.end());
            einsums::initialize(argv);
            Py_AtExit(&einsums_python_atexit);
        },
        py::arg("cli_options") = std::vector<std::string>{},
        "Start the einsums runtime from einsums.rc if it is not already running.\n"
        "cli_options: extra ``--einsums:*`` flags, appended after the rc-derived\n"
        "ones so they take precedence.");

    m.def("_is_initialized", []() { return einsums::is_running(); }, "Returns True if the einsums runtime has been initialized.");

    // The live registry, so a test can check the generated rc.py against it.
    m.def(
        "_registered_options",
        []() {
            py::list out;
            for (auto const &opt : einsums::cl::registered_options()) {
                py::dict d;
                d["name"]             = opt.name;
                d["key"]              = opt.key;
                d["attribute"]        = rc_attribute_name(opt.name);
                d["negated_name"]     = opt.negated_name;
                d["env"]              = opt.env_name;
                d["help"]             = opt.help;
                d["category"]         = opt.category;
                d["value_name"]       = opt.value_name;
                d["kind"]             = opt.kind == einsums::cl::OptionKind::Flag ? "flag" : "value";
                d["computed_default"] = opt.computed_default;
                switch (opt.type) {
                case einsums::cl::OptionType::Bool:
                    d["type"]    = "bool";
                    d["default"] = opt.default_bool;
                    break;
                case einsums::cl::OptionType::Int:
                    d["type"]    = "int";
                    d["default"] = opt.default_int;
                    break;
                case einsums::cl::OptionType::Double:
                    d["type"]    = "float";
                    d["default"] = opt.default_double;
                    break;
                case einsums::cl::OptionType::String:
                    d["type"]    = "str";
                    d["default"] = opt.default_string;
                    break;
                }
                out.append(std::move(d));
            }
            return out;
        },
        "Every option a descriptor registered, as dicts: name, key, the einsums.rc\n"
        "attribute it maps to, kind, value type, and declared default. The generated\n"
        "``--no-`` twin of a flag is named by ``negated_name`` rather than listed.");

    m.def(
        "_argv_from_rc", []() { return argv_from_rc(py::module_::import("einsums.rc")); },
        "The argv einsums.rc's current settings would start the runtime with.\n"
        "Exposed so a test can check that every field reaches a real flag; calling it\n"
        "has no effect on a runtime that is already up.");

    // --- sealed worlds ------------------------------------------------------
    //
    // Which libEinsums this extension bound to; the stage loader refuses a module that disagrees.
    // Bound by hand to avoid enabling apiary codegen for Config, the lowest module.
    m.attr("__einsums_world__") = reinterpret_cast<std::uintptr_t>(einsums::sealed::world().identity);

    m.def(
        "_world_info",
        []() {
            einsums::sealed::WorldInfo const &w = einsums::sealed::world();
            py::dict                          d;
            d["identity"]           = reinterpret_cast<std::uintptr_t>(w.identity);
            d["config_fingerprint"] = w.config_fingerprint;
            d["layout_fingerprint"] = w.layout_fingerprint;
            d["version"]            = std::string(w.version_string);
            d["version_major"]      = w.version_major;
            d["version_minor"]      = w.version_minor;
            d["version_patch"]      = w.version_patch;
            d["git_commit"]         = std::string(w.git_commit);
            d["compiler"]           = std::string(w.compiler_id);
            d["compiler_major"]     = w.compiler_major;
            d["library_path"]       = std::string(w.library_path);
            return d;
        },
        "Identity and build fingerprint of the libEinsums this extension is bound to.\n"
        "Compared against a stage module's own record to refuse a cross-world load.");

    m.def(
        "_mapped_einsums_libraries", []() { return einsums::sealed::mapped_einsums_libraries(); },
        "Paths of every libEinsums mapped into this process.\n"
        "More than one entry means more than one world; empty means the platform\n"
        "offers no way to enumerate loaded images.");

    m.def(
        "_register_stage_module", [](std::string const &name) { return einsums::sealed::register_stage_module(name.c_str()); },
        py::arg("name"), "Record a stage module against THIS libEinsums. Returns False if already recorded.");

    m.def(
        "_stage_module_registered", [](std::string const &name) { return einsums::sealed::stage_module_registered(name.c_str()); },
        py::arg("name"),
        "Whether a stage module registered against THIS libEinsums.\n"
        "False for a module that bound to a different copy: its registration went\n"
        "into that copy's table, which is what makes this a cross-world check.");

    m.def(
        "_registered_stage_modules", []() { return einsums::sealed::registered_stage_modules(); },
        "Every stage module recorded against THIS libEinsums, in load order.\n"
        "Worth printing when a handshake fails: it names the modules that DID reach\n"
        "this world, against the one that did not.");

    apiary_register_all(m);
}
