//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// NO include guard on purpose: this header is a template that stamps the
// kernel bodies into whatever namespace the includer names, and one TU may
// legitimately include it more than once under different namespaces.
//
// BLIS-style register-blocked micro-kernel bodies.
//
// Everything in this header is wrapped in EINSUMS_PACKED_GEMM_KERNEL_NS,
// which the includer MUST define first, so that the per-rung translation
// units generated by einsums_add_simd_dispatch_sources() (see
// src/MicroKernelImpl.cpp) each get their own copies with distinct mangled
// names — the codegen of a rung compiled with -march=x86-64-v3 must never
// be ODR-folded with a baseline copy. MicroKernel.hpp includes it under
// arch_ambient for the exotic-element-type fallback. The macro is consumed
// (undefined) at the end of this header.

#include <Einsums/Config/Namespace.hpp>
#include <Einsums/SIMD/Operations.hpp>
#include <Einsums/SIMD/Platform.hpp>
#include <Einsums/SIMD/Vec.hpp>

#include <cstdint>
#include <type_traits>

// Loop-unrolling pragma for the fixed-trip register loops below. GCC ignores
// clang's bare `#pragma unroll` and spells its own; MSVC has neither, and its
// optimizer unrolls short constant-trip loops on its own.
#if defined(__clang__)
#    define EINSUMS_PACKED_GEMM_UNROLL(n) _Pragma("unroll")
#elif defined(__GNUC__)
#    define EINSUMS_PACKED_GEMM_UNROLL_STR(x) #x
#    define EINSUMS_PACKED_GEMM_UNROLL(n)     _Pragma(EINSUMS_PACKED_GEMM_UNROLL_STR(GCC unroll n))
#else
#    define EINSUMS_PACKED_GEMM_UNROLL(n)
#endif

#if !defined(EINSUMS_PACKED_GEMM_KERNEL_NS)
#    error "Define EINSUMS_PACKED_GEMM_KERNEL_NS before including MicroKernelBody.hpp"
#endif

EINSUMS_NAMESPACE_BEGIN(packed_gemm)
namespace EINSUMS_PACKED_GEMM_KERNEL_NS {

/// @brief Compute one MR*NR tile: C[i*rs_c + j*cs_c] += alpha * Sum_k Ap[i + k*MR] * Bp[k*NR + j].
///
/// Ap is a column-major MR*kc panel, Bp a row-major kc*NR panel — the layouts
/// produced by pack_A / pack_B. Both panels are zero-padded to full MR/NR by
/// the packers, so the accumulation always runs the full register block; only
/// the C store is masked to mr_eff * nr_eff.
///
/// The accumulator array has compile-time extents and fully unrolled
/// update/store loops, so clang keeps it in vector registers (NEON: MR=4,NR=6
/// doubles = 12 float64x2 accumulators) and fuses the multiply-adds. Which
/// instruction set those registers belong to is decided by the flags of the
/// enclosing rung TU.
template <typename T, int MR, int NR>
void micro_kernel(int64_t kc, T alpha, T const *__restrict Ap, T const *__restrict Bp, int64_t mr_eff, int64_t nr_eff, T *C, int64_t rs_c,
                  int64_t cs_c) {
    T acc[MR][NR] = {};

    for (int64_t k = 0; k < kc; ++k) {
        T const *__restrict a = Ap + k * MR;
        T const *__restrict b = Bp + k * NR;
#pragma unroll
        for (int j = 0; j < NR; ++j) {
            T const bj = b[j];
#pragma unroll
            for (int i = 0; i < MR; ++i) {
                acc[i][j] += a[i] * bj;
            }
        }
    }

    if (mr_eff == MR && nr_eff == NR) {
#pragma unroll
        for (int j = 0; j < NR; ++j) {
#pragma unroll
            for (int i = 0; i < MR; ++i) {
                C[i * rs_c + j * cs_c] += alpha * acc[i][j];
            }
        }
    } else {
        for (int64_t j = 0; j < nr_eff; ++j) {
            for (int64_t i = 0; i < mr_eff; ++i) {
                C[i * rs_c + j * cs_c] += alpha * acc[i][j];
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Rung-width vector kernel
// ---------------------------------------------------------------------------
//
// The portable body above leaves vectorization to the compiler, and what the
// compiler makes of `acc[MR][NR]` depends on MR matching the register it
// has. That match used to come from cpu_config()'s VL, which is the width of
// the ISA the LIBRARY was compiled for (SSE2 on a distribution build), not the
// width of the rung this TU is compiled at: on an AVX2 machine the v3 rung
// was asked for a 4x6 tile and produced SSE-width code, and measured 15 GF/s
// for float where a 16x6 tile of the same rung reaches 61 GF/s on the same
// packed block (Zen+, single core; OpenBLAS' full sgemm runs 57 GF/s there).
//
// So the tile is stated in the rung's own vectors: MR is two of them along
// m, NR is six broadcast columns, twelve accumulators, which fits the sixteen
// registers of SSE/AVX/NEON and the thirty-two of AVX-512 alike. The shape is
// a compile-time fact of this TU (@ref vector_kernel_mr), and
// micro_kernel_block() reports it so the packers cut panels to match.
//
// Only float and double have it; the complex bodies stay on the portable
// kernel (the rungs that care route complex through 1m or 3m anyway).

/// True when this rung has a vector register to build the tile from.
template <typename T>
inline constexpr bool has_vector_kernel = (std::is_same_v<T, float> || std::is_same_v<T, double>) && einsums::simd::native_bits > 0;

/// M register-block of the vector kernel: two of this rung's vectors.
template <typename T>
inline constexpr int vector_kernel_mr = 2 * einsums::simd::native_lanes<T>;

/// N register-block of the vector kernel: six broadcast columns.
inline constexpr int vector_kernel_nr = 6;

/// @brief One (2 * lanes) x 6 tile through this rung's vector registers.
///
/// Same contract as @ref micro_kernel: Ap is a column-major MR*kc panel, Bp a
/// row-major kc*NR panel, both zero-padded by the packers, and only the C
/// update is masked to mr_eff x nr_eff. A full tile into a unit-row-stride
/// C (rs_c == 1, the column-major case every scatter temp and every
/// column-major C presents) loads, scales and stores whole vectors; anything
/// else goes through a small stack tile so the accumulation loop never
/// branches on the C layout.
template <typename T>
void micro_kernel_vector(int64_t kc, T alpha, T const *__restrict Ap, T const *__restrict Bp, int64_t mr_eff, int64_t nr_eff, T *C,
                         int64_t rs_c, int64_t cs_c) {
    namespace simd   = einsums::simd;
    constexpr int L  = simd::native_lanes<T>;
    constexpr int MR = vector_kernel_mr<T>;
    constexpr int NR = vector_kernel_nr;

    simd::Vec<T> acc0[NR];
    simd::Vec<T> acc1[NR];
    EINSUMS_PACKED_GEMM_UNROLL(6)
    for (int j = 0; j < NR; ++j) {
        acc0[j] = simd::broadcast(T{0});
        acc1[j] = simd::broadcast(T{0});
    }

    for (int64_t k = 0; k < kc; ++k) {
        simd::Vec<T> const a0 = simd::loadu(Ap + k * MR);
        simd::Vec<T> const a1 = simd::loadu(Ap + k * MR + L);
        T const *__restrict b = Bp + k * NR;
        EINSUMS_PACKED_GEMM_UNROLL(6)
        for (int j = 0; j < NR; ++j) {
            simd::Vec<T> const bj = simd::broadcast(b[j]);
            acc0[j]               = simd::fmadd(a0, bj, acc0[j]);
            acc1[j]               = simd::fmadd(a1, bj, acc1[j]);
        }
    }

    simd::Vec<T> const va = simd::broadcast(alpha);
    if (rs_c == 1 && mr_eff == MR && nr_eff == NR) {
        EINSUMS_PACKED_GEMM_UNROLL(6)
        for (int j = 0; j < NR; ++j) {
            T *c = C + j * cs_c;
            simd::storeu(c, simd::fmadd(va, acc0[j], simd::loadu(c)));
            simd::storeu(c + L, simd::fmadd(va, acc1[j], simd::loadu(c + L)));
        }
        return;
    }

    alignas(64) T tile[MR * NR];
    EINSUMS_PACKED_GEMM_UNROLL(6)
    for (int j = 0; j < NR; ++j) {
        simd::storeu(tile + j * MR, acc0[j]);
        simd::storeu(tile + j * MR + L, acc1[j]);
    }
    for (int64_t j = 0; j < nr_eff; ++j) {
        for (int64_t i = 0; i < mr_eff; ++i) {
            C[i * rs_c + j * cs_c] += alpha * tile[j * MR + i];
        }
    }
}

/// @brief Variable-block fallback for (MR, NR) shapes without a static instantiation.
template <typename T>
void micro_kernel_generic(int64_t kc, T alpha, T const *Ap, T const *Bp, int mr_block, int nr_block, int64_t mr_eff, int64_t nr_eff, T *C,
                          int64_t rs_c, int64_t cs_c) {
    for (int64_t j = 0; j < nr_eff; ++j) {
        for (int64_t i = 0; i < mr_eff; ++i) {
            T sum{};
            for (int64_t k = 0; k < kc; ++k) {
                sum += Ap[i + k * mr_block] * Bp[k * nr_block + j];
            }
            C[i * rs_c + j * cs_c] += alpha * sum;
        }
    }
}

/// @brief Dispatch to the kernel matching the runtime block sizes.
///
/// The rung's own tile (@ref vector_kernel_mr x 6) takes the vector kernel.
/// The portable bodies cover MR in {4, 8, 16} with NR 6, the shapes
/// cpu_config() produces (2*VL for SSE/NEON, AVX, AVX-512); anything else
/// falls back to the generic kernel.
template <typename T>
void micro_kernel_run(int mr_block, int nr_block, int64_t kc, T alpha, T const *Ap, T const *Bp, int64_t mr_eff, int64_t nr_eff, T *C,
                      int64_t rs_c, int64_t cs_c) {
    if constexpr (has_vector_kernel<T>) {
        if (mr_block == vector_kernel_mr<T> && nr_block == vector_kernel_nr) {
            micro_kernel_vector<T>(kc, alpha, Ap, Bp, mr_eff, nr_eff, C, rs_c, cs_c);
            return;
        }
    }
    if (nr_block == 6) {
        switch (mr_block) {
        case 4:
            micro_kernel<T, 4, 6>(kc, alpha, Ap, Bp, mr_eff, nr_eff, C, rs_c, cs_c);
            return;
        case 8:
            micro_kernel<T, 8, 6>(kc, alpha, Ap, Bp, mr_eff, nr_eff, C, rs_c, cs_c);
            return;
        case 16:
            micro_kernel<T, 16, 6>(kc, alpha, Ap, Bp, mr_eff, nr_eff, C, rs_c, cs_c);
            return;
        default:
            break;
        }
    }
    micro_kernel_generic<T>(kc, alpha, Ap, Bp, mr_block, nr_block, mr_eff, nr_eff, C, rs_c, cs_c);
}

} // namespace EINSUMS_PACKED_GEMM_KERNEL_NS
EINSUMS_NAMESPACE_END(packed_gemm)

#undef EINSUMS_PACKED_GEMM_UNROLL
#undef EINSUMS_PACKED_GEMM_UNROLL_STR
#undef EINSUMS_PACKED_GEMM_KERNEL_NS
