//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// NO include guard on purpose: this header is a template that stamps the
// kernel bodies into whatever namespace the includer names, and one TU may
// legitimately include it more than once under different namespaces.
//
// BLIS-style register-blocked micro-kernel bodies.
//
// Everything in this header is wrapped in EINSUMS_PACKED_GEMM_KERNEL_NS,
// which the includer MUST define first, so that the per-rung translation
// units generated by einsums_add_simd_dispatch_sources() (see
// src/MicroKernelImpl.cpp) each get their own copies with distinct mangled
// names — the codegen of a rung compiled with -march=x86-64-v3 must never
// be ODR-folded with a baseline copy. MicroKernel.hpp includes it under
// arch_ambient for the exotic-element-type fallback. The macro is consumed
// (undefined) at the end of this header.

#include <cstdint>

#if !defined(EINSUMS_PACKED_GEMM_KERNEL_NS)
#    error "Define EINSUMS_PACKED_GEMM_KERNEL_NS before including MicroKernelBody.hpp"
#endif

namespace einsums::packed_gemm {
namespace EINSUMS_PACKED_GEMM_KERNEL_NS {

/// @brief Compute one MR*NR tile: C[i*rs_c + j*cs_c] += alpha * Sum_k Ap[i + k*MR] * Bp[k*NR + j].
///
/// Ap is a column-major MR*kc panel, Bp a row-major kc*NR panel — the layouts
/// produced by pack_A / pack_B. Both panels are zero-padded to full MR/NR by
/// the packers, so the accumulation always runs the full register block; only
/// the C store is masked to mr_eff * nr_eff.
///
/// The accumulator array has compile-time extents and fully unrolled
/// update/store loops, so clang keeps it in vector registers (NEON: MR=4,NR=6
/// doubles = 12 float64x2 accumulators) and fuses the multiply-adds. Which
/// instruction set those registers belong to is decided by the flags of the
/// enclosing rung TU.
template <typename T, int MR, int NR>
void micro_kernel(int64_t kc, T alpha, T const *__restrict Ap, T const *__restrict Bp, int64_t mr_eff, int64_t nr_eff, T *C, int64_t rs_c,
                  int64_t cs_c) {
    T acc[MR][NR] = {};

    for (int64_t k = 0; k < kc; ++k) {
        T const *__restrict a = Ap + k * MR;
        T const *__restrict b = Bp + k * NR;
#pragma unroll
        for (int j = 0; j < NR; ++j) {
            T const bj = b[j];
#pragma unroll
            for (int i = 0; i < MR; ++i) {
                acc[i][j] += a[i] * bj;
            }
        }
    }

    if (mr_eff == MR && nr_eff == NR) {
#pragma unroll
        for (int j = 0; j < NR; ++j) {
#pragma unroll
            for (int i = 0; i < MR; ++i) {
                C[i * rs_c + j * cs_c] += alpha * acc[i][j];
            }
        }
    } else {
        for (int64_t j = 0; j < nr_eff; ++j) {
            for (int64_t i = 0; i < mr_eff; ++i) {
                C[i * rs_c + j * cs_c] += alpha * acc[i][j];
            }
        }
    }
}

/// @brief Variable-block fallback for (MR, NR) shapes without a static instantiation.
template <typename T>
void micro_kernel_generic(int64_t kc, T alpha, T const *Ap, T const *Bp, int mr_block, int nr_block, int64_t mr_eff, int64_t nr_eff, T *C,
                          int64_t rs_c, int64_t cs_c) {
    for (int64_t j = 0; j < nr_eff; ++j) {
        for (int64_t i = 0; i < mr_eff; ++i) {
            T sum{};
            for (int64_t k = 0; k < kc; ++k) {
                sum += Ap[i + k * mr_block] * Bp[k * nr_block + j];
            }
            C[i * rs_c + j * cs_c] += alpha * sum;
        }
    }
}

/// @brief Dispatch to the static instantiation matching the runtime block sizes.
///
/// cpu_config() produces MR in {4, 8, 16} (2*VL for SSE/NEON, AVX, AVX-512)
/// and NR fixed at 6; anything else falls back to the generic kernel.
template <typename T>
void micro_kernel_run(int mr_block, int nr_block, int64_t kc, T alpha, T const *Ap, T const *Bp, int64_t mr_eff, int64_t nr_eff, T *C,
                      int64_t rs_c, int64_t cs_c) {
    if (nr_block == 6) {
        switch (mr_block) {
        case 4:
            micro_kernel<T, 4, 6>(kc, alpha, Ap, Bp, mr_eff, nr_eff, C, rs_c, cs_c);
            return;
        case 8:
            micro_kernel<T, 8, 6>(kc, alpha, Ap, Bp, mr_eff, nr_eff, C, rs_c, cs_c);
            return;
        case 16:
            micro_kernel<T, 16, 6>(kc, alpha, Ap, Bp, mr_eff, nr_eff, C, rs_c, cs_c);
            return;
        default:
            break;
        }
    }
    micro_kernel_generic<T>(kc, alpha, Ap, Bp, mr_block, nr_block, mr_eff, nr_eff, C, rs_c, cs_c);
}

} // namespace EINSUMS_PACKED_GEMM_KERNEL_NS
} // namespace einsums::packed_gemm

#undef EINSUMS_PACKED_GEMM_KERNEL_NS
