# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.

"""``einsums completion bash|zsh|fish``: a shell completion script for ``einsums``.

Generated from the argument parsers themselves, including the ones ``profiler`` and
``stages`` forward to, so the completions cannot fall behind the options. Install with,
for example, ``einsums completion bash > ~/.local/share/bash-completion/completions/einsums``.
"""

from __future__ import annotations

import argparse
import shlex


def register(subparsers) -> None:
    p = subparsers.add_parser("completion", help="Print a shell completion script (bash, zsh or fish)")
    p.add_argument("shell", choices=("bash", "zsh", "fish"))
    p.set_defaults(func=run)


def _walk(parser: argparse.ArgumentParser, path: tuple[str, ...], out: dict) -> None:
    """Map each command path to (subcommands, options) by walking the parser tree."""
    subcommands: list[str] = []
    options: list[str] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, child in action.choices.items():
                subcommands.append(name)
                _walk(child, (*path, name), out)
        else:
            options += [o for o in action.option_strings if o.startswith("--") or len(o) == 2]
    out[path] = (subcommands, sorted(set(options)))


def command_tree(prog: str = "einsums") -> dict[tuple[str, ...], tuple[list[str], list[str]]]:
    from waggle.cli import viewer_parser
    from waggle.report import add_parsers

    from . import build_parser
    from ..stages.__main__ import build_parser as stages_parser

    tree: dict = {}
    _walk(build_parser(prog), (), tree)
    # The forwarding commands: replace their opaque REMAINDER entry with the real parsers.
    viewer = viewer_parser(f"{prog} profiler", "--einsums:profile:server")
    add_parsers(viewer.add_subparsers())
    _walk(viewer, ("profiler",), tree)
    _walk(stages_parser(f"{prog} stages"), ("stages",), tree)
    return tree


def bash(tree: dict) -> str:
    cases = []
    for path, (subs, opts) in sorted(tree.items()):
        key = " ".join(path)
        cases.append(f"        {shlex.quote(key)}) subs={shlex.quote(' '.join(subs))}; opts={shlex.quote(' '.join(opts))} ;;")
    return f"""# einsums completion for bash (generated by `einsums completion bash`)
_einsums_complete() {{
    local cur path word candidate subs opts
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    path=""
    # The longest known command path made of the words before the cursor.
    for word in "${{COMP_WORDS[@]:1:COMP_CWORD-1}}"; do
        candidate="${{path:+$path }}$word"
        _einsums_lookup "$candidate" && path="$candidate"
    done
    _einsums_lookup "$path"
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    elif [[ -n "$subs" ]]; then
        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    else
        COMPREPLY=( $(compgen -f -- "$cur") )
    fi
}}
_einsums_lookup() {{
    subs=""; opts=""
    case "$1" in
{chr(10).join(cases)}
        *) return 1 ;;
    esac
    return 0
}}
complete -o filenames -F _einsums_complete einsums
"""


def zsh(tree: dict) -> str:
    return "# einsums completion for zsh, through its bash compatibility layer\n" \
        "autoload -U +X bashcompinit && bashcompinit\n" + bash(tree)


def fish(tree: dict) -> str:
    lines = ["# einsums completion for fish (generated by `einsums completion fish`)", "complete -c einsums -f"]
    for path, (subs, opts) in sorted(tree.items()):
        if path:
            # True once the path's words have been typed, and none of its subcommands yet.
            seen = " && ".join(f"__fish_seen_subcommand_from {w}" for w in path)
            cond = seen + (f" && not __fish_seen_subcommand_from {' '.join(subs)}" if subs else "")
        else:
            cond = "__fish_use_subcommand"
        for sub in subs:
            lines.append(f"complete -c einsums -n {shlex.quote(cond)} -a {shlex.quote(sub)}")
        for opt in opts:
            flag = f"-l {opt[2:]}" if opt.startswith("--") else f"-s {opt[1:]}"
            lines.append(f"complete -c einsums -n {shlex.quote(cond)} {flag}")
        if path and not subs:
            lines.append(f"complete -c einsums -n {shlex.quote(cond)} -F")
    return "\n".join(lines) + "\n"


def run(args: argparse.Namespace) -> int:
    tree = command_tree(args.top_prog if args.top_prog != "python -m einsums" else "einsums")
    print({"bash": bash, "zsh": zsh, "fish": fish}[args.shell](tree), end="")
    return 0
