//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from dlpno.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: e03f70dcab2ee04201053e6c1e5301e0

/// @file
/// The C++ backend of the `compute_pno_integrals` stage.
///
/// The other half of the Python implementation in `dlpno.stages`. Both
/// implement the same contract, both are selectable at runtime, and they are
/// compared against each other rather than one being retired.

#pragma once

#include <Einsums/Tensor/RuntimeTensor.hpp>

#include <cstdint>
#include <dlpno/Contracts.hpp>
#include <vector>

namespace dlpno {

/// Every PNO-basis integral block one chunk of pairs needs.
///
/// The first COUPLED-CLUSTER phase to state a contract, and the third stage
/// overall: seventeen parameters against the nineteen `self` attributes the
/// phase measured before `_plan_chunk` was split away, two of which were not
/// state at all (a print helper and a method). Design decision 6 asked for the
/// phase to be kept promotable and `stage_state_report.py` is how that was
/// checked; this is the promotion it was kept narrow for.
///
/// Promoted because its measured shape is the promotion signature exactly:
/// parity with psi4 at one thread, several times adrift at ten, on a long
/// per-pair chain of fits, GEMMs and gathers that psi4 threads over pairs.
/// Python cannot drive that loop concurrently - against the OpenMP-built
/// OpenBLAS a caller-created thread pool returns silently wrong numbers (trap
/// 7) - so the C++ backend is the only place the per-pair chains can overlap.
///
/// One chunk of pairs at a time, because the blocks a pair is BUILT from are an
/// order larger than the blocks it produces and the whole set does not fit in
/// core. The chunking is the caller's (`dlpno.cc_integrals._chunks`),
/// which is what keeps it a memory decision rather than a numerical one: no
/// pair reads another pair's raw blocks, so any split gives bit-identical
/// integrals.
///
/// @param q_ij     Three-index integrals `(Q | i j)`, the full tensor.
/// @param q_ia     Three-index integrals `(Q | i u)`, the full tensor.
/// @param q_ab     Three-index integrals `(Q | u v)`, the full tensor.
/// @param metric   The auxiliary-basis metric `(P | Q)`, the full matrix.
/// @param X_pno    Per pair in the chunk, its own PAO domain -> PNO transform.
/// @param i_lmo    Per pair, LMO `i`.
/// @param j_lmo    Per pair, LMO `j`; never less than `i`.
/// @param n_pno    Per pair, its PNO count.
/// @param strong   Per pair, whether it is a strong pair. The density-fitted
///                 factors and both non-projected families are built for strong pairs
///                 only, exactly as psi4 does, because only their residual reads them.
/// @param ribfs    Per pair, the auxiliary indices of its fit domain.
/// @param paos     Per pair, the PAO indices its own domain covers.
/// @param lmos     Per pair, the LMOs it interacts with.
/// @param extended Per pair, its PAO domain widened by every interacting LMO's,
///                 which is the basis the non-projected families go through.
/// @param rot_X    The PNO transform of every neighbour pair this chunk reads,
///                 deduplicated: a neighbour is shared by many pairs.
/// @param rot_paos Parallel to `rot_X`, that neighbour pair's PAO domain, from
///                 which the numerics recovers its position inside `extended`.
/// @param nb_ij    Per pair, per interacting LMO `k`, the index into `rot_X` of
///                 pair `(k, j)`, or `-1` when it does not exist or has no PNOs.
///                 Empty for a weak pair, which reads no neighbour block at all.
/// @param nb_ji    The same for pair `(k, i)`, which the `ji` blocks read.
///                 Empty on the diagonal, where there are no `ji` blocks.
[[nodiscard]] PnoIntegralBlocks
compute_pno_integrals(einsums::RuntimeTensor<double> const &q_ij, einsums::RuntimeTensor<double> const &q_ia,
                      einsums::RuntimeTensor<double> const &q_ab, einsums::RuntimeTensor<double> const &metric,
                      std::vector<einsums::RuntimeTensor<double>> const &X_pno, std::vector<std::int64_t> const &i_lmo,
                      std::vector<std::int64_t> const &j_lmo, std::vector<std::int64_t> const &n_pno, std::vector<bool> const &strong,
                      std::vector<std::vector<std::int64_t>> const &ribfs, std::vector<std::vector<std::int64_t>> const &paos,
                      std::vector<std::vector<std::int64_t>> const &lmos, std::vector<std::vector<std::int64_t>> const &extended,
                      std::vector<einsums::RuntimeTensor<double>> const &rot_X, std::vector<std::vector<std::int64_t>> const &rot_paos,
                      std::vector<std::vector<std::int64_t>> const &nb_ij, std::vector<std::vector<std::int64_t>> const &nb_ji);

} // namespace dlpno
