//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from dlpno.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: d53b922354733bd7b6c42550ece0b80a

/// @file
/// The C++ backend of the `compute_pno_overlaps` stage.
///
/// The other half of the Python implementation in `dlpno.stages`. Both
/// implement the same contract, both are selectable at runtime, and they are
/// compared against each other rather than one being retired.

#pragma once

#include <Einsums/Tensor/RuntimeTensor.hpp>

#include <cstdint>
#include <dlpno/Contracts.hpp>
#include <vector>

namespace dlpno {

/// Overlaps between every coupled pair of PNO bases, scaled by the Fock element.
///
/// The first DLPNO phase to state a contract. Seven parameters, against the 27
/// fields of `self` the phase touched before it was split - which is what
/// "cut where the interface is narrow" means in practice, and why the split
/// had to come first.
///
/// Runs to completion and returns values; it does not emit into an ambient
/// capture. That is a structural property rather than an unfinished one: the
/// phase runs two graphs with a host-side scaling between them, and the second
/// graph's inputs are the first graph's outputs after that scaling. There is
/// no single graph to emit into until the scaling itself becomes a captured
/// op, at which point the stage stops being `eager` and the report loses a
/// SPLIT. So this stage is not what proves the shared-graph contract; a
/// separate, deliberately minimal stage does that.
///
/// @param X_pno           Per pair, the PNO transform on its own domain.
/// @param S_pao           PAO overlap matrix, `(npao, npao)`.
/// @param lmopair_to_paos Per pair, the PAO indices its domain covers.
/// @param n_pno           Per pair, its PNO count; zero means the pair is dead.
/// @param bucket_of       Per pair, which padding bucket it is stored at.
/// @param bucket_dims     Per bucket, the padded block dimension.
/// @param plan            The layout, from `plan_pno_couplings`.
[[nodiscard]] PnoOverlaps compute_pno_overlaps(std::vector<einsums::RuntimeTensor<double>> const &X_pno,
                                               einsums::RuntimeTensor<double> const              &S_pao,
                                               std::vector<std::vector<std::int64_t>> const      &lmopair_to_paos,
                                               std::vector<std::int64_t> const &n_pno, std::vector<std::int64_t> const &bucket_of,
                                               std::vector<std::int64_t> const &bucket_dims, CouplingPlan const &plan);

} // namespace dlpno
