//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from dlpno.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: d780745cc26c3a3bcd284c5e477ce2cf

/// @file
/// Cross-boundary contract aggregates for the dlpno stages.
///
/// One struct per `@contract` dataclass reachable from `dlpno.stages`,
/// field for field. That correspondence IS the contract; it is what
/// `python -m einsums.stages check` verifies, and it is why this file is
/// generated rather than written. The prose below is carried across from the
/// Python `#:` comments and docstrings, so the rationale lives in one place
/// and cannot be lost by regenerating this header.

#pragma once

#include <Einsums/Tensor/RuntimeTensor.hpp>

#include <cstdint>
#include <utility>
#include <vector>

namespace dlpno {

/// Which pairs couple to which partners, and where every block goes.
///
/// Pure index bookkeeping: no floating-point array appears here, and nothing in
/// it depends on the values of the integrals. That is what makes it the natural
/// seam. The planning is where the method's *logic* lives and is cheap; the
/// numerics it describes are where the time goes.
///
/// Two layouts are described at once, because the residual's two halves want
/// opposite groupings and the couplings are a bipartite graph, so no single
/// order serves both. `dest_slot` is the pair-major position, `src_slot`
/// the partner-major one, and `inv_perm` maps partner-major back to
/// pair-major for the transposed copy.
///
/// Structure of arrays, chosen for the C++ side's benefit: a dict of lists of
/// tuples would arrive there as a pointer chase per coupling, and the whole
/// reason this stage is in C++ is to walk 32,948 couplings without one.
///
/// Mirrors `dlpno.contracts.CouplingPlan`, field for field.
///
/// The Python contract declares `pair`, `partner`, `cls`, `dest_slot`, `src_slot`, `sign`, `factor` parallel: always the same length,
/// indexed by one ordinal. The caster checks it, because a short array here is a silent out-of-bounds read rather than an exception.
struct CouplingPlan {
    /// `(bucket of the pair, bucket of the partner)` for each class, in ascending order. The class ORDINAL is the identity everywhere else;
    /// this is only how a class recovers its two block dimensions.
    std::vector<std::pair<std::int64_t, std::int64_t>> classes;
    /// Columns in the pair-major layout, excluding the reserved zero slot.
    std::vector<std::int64_t> slots_pair;
    /// Columns in the partner-major layout, including the reserved zero slot.
    std::vector<std::int64_t> slots_partner;
    /// For each partner-major slot, the pair-major slot it came from. Padding points at the reserved slot past the end of the pair-major
    /// side, so a gather writes its whole destination and the padded columns are genuinely zero rather than stale.
    std::vector<std::vector<std::int64_t>> inv_perm;
    std::vector<std::int64_t>              pair;
    std::vector<std::int64_t>              partner;
    /// Class ordinal, indexing `classes` and every other per-class list.
    std::vector<std::int64_t> cls;
    std::vector<std::int64_t> dest_slot;
    std::vector<std::int64_t> src_slot;
    /// Sign of the Fock element. Rides on the transposed copy only: `S` appears on both sides of the congruence, so a sign in both would
    /// square away.
    std::vector<double> sign;
    /// The Fock element itself. Its square root scales the pair-major copy.
    std::vector<double> factor;
    /// Pairs with at least one coupling, ascending. Derivable from `pair`, carried because every consumer needs it and rebuilding a sorted
    /// unique set per call is work the planner already did.
    std::vector<std::int64_t> coupled_pairs;
};

/// The overlap tensors, one per shape class, in both layouts.
///
/// `close` rather than `exact` because the two backends reach these through
/// different orderings of the same GEMMs, so agreement is to floating-point
/// tolerance rather than bit for bit.
///
/// Mirrors `dlpno.contracts.PnoOverlaps`, field for field.
struct PnoOverlaps {
    /// Pair-major, `(M_b, M_p * (slots_pair + 1))` per class, already scaled by `sqrt|factor|`.
    std::vector<einsums::RuntimeTensor<double>> S_cls;
    /// Partner-major, `(M_p, M_b, slots_partner)` per class, carrying `sqrt|factor|` from the copy it was lifted from and the sign of its
    /// own.
    std::vector<einsums::RuntimeTensor<double>> S_T;
};

} // namespace dlpno
