//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from dlpno.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: a7c3e742719ba70a5ec8d19f4dd45c2b

/// @file
/// Cross-boundary contract aggregates for the dlpno stages.
///
/// One struct per `@contract` dataclass reachable from `dlpno.stages`,
/// field for field. That correspondence IS the contract; it is what
/// `python -m einsums.stages check` verifies, and it is why this file is
/// generated rather than written. The prose below is carried across from the
/// Python `#:` comments and docstrings, so the rationale lives in one place
/// and cannot be lost by regenerating this header.

#pragma once

#include <Einsums/Tensor/RuntimeTensor.hpp>

#include <cstdint>
#include <utility>
#include <vector>

namespace dlpno {

/// Which pairs couple to which partners, and where every block goes.
///
/// Pure index bookkeeping: no floating-point array appears here, and nothing in
/// it depends on the values of the integrals. That is what makes it the natural
/// seam. The planning is where the method's *logic* lives and is cheap; the
/// numerics it describes are where the time goes.
///
/// Two layouts are described at once, because the residual's two halves want
/// opposite groupings and the couplings are a bipartite graph, so no single
/// order serves both. `dest_slot` is the pair-major position, `src_slot`
/// the partner-major one, and `inv_perm` maps partner-major back to
/// pair-major for the transposed copy.
///
/// Structure of arrays, chosen for the C++ side's benefit: a dict of lists of
/// tuples would arrive there as a pointer chase per coupling, where the flat
/// arrays make the operand loop a linear scan over 32,948 of them.
///
/// Mirrors `dlpno.contracts.CouplingPlan`, field for field.
///
/// The Python contract declares `pair`, `partner`, `cls`, `dest_slot`, `src_slot`, `sign`, `factor` parallel: always the same length,
/// indexed by one ordinal. The caster checks it, because a short array here is a silent out-of-bounds read rather than an exception.
struct CouplingPlan {
    /// `(bucket of the pair, bucket of the partner)` for each class, in ascending order. The class ORDINAL is the identity everywhere else;
    /// this is only how a class recovers its two block dimensions.
    std::vector<std::pair<std::int64_t, std::int64_t>> classes;
    /// Columns in the pair-major layout, excluding the reserved zero slot.
    std::vector<std::int64_t> slots_pair;
    /// Columns in the partner-major layout, including the reserved zero slot.
    std::vector<std::int64_t> slots_partner;
    /// For each partner-major slot, the pair-major slot it came from. Padding points at the reserved slot past the end of the pair-major
    /// side, so a gather writes its whole destination and the padded columns are genuinely zero rather than stale.
    std::vector<std::vector<std::int64_t>> inv_perm;
    std::vector<std::int64_t>              pair;
    std::vector<std::int64_t>              partner;
    /// Class ordinal, indexing `classes` and every other per-class list.
    std::vector<std::int64_t> cls;
    std::vector<std::int64_t> dest_slot;
    std::vector<std::int64_t> src_slot;
    /// Sign of the Fock element. Rides on the transposed copy only: `S` appears on both sides of the congruence, so a sign in both would
    /// square away.
    std::vector<double> sign;
    /// The Fock element itself. Its square root scales the pair-major copy.
    std::vector<double> factor;
    /// Pairs with at least one coupling, ascending. Derivable from `pair`, carried because every consumer needs it and rebuilding a sorted
    /// unique set per call is work the planner already did.
    std::vector<std::int64_t> coupled_pairs;
};

/// The overlap tensors, one per shape class, in both layouts.
///
/// `close` rather than `exact` because the two backends reach these through
/// different orderings of the same GEMMs, so agreement is to floating-point
/// tolerance rather than bit for bit.
///
/// Mirrors `dlpno.contracts.PnoOverlaps`, field for field.
struct PnoOverlaps {
    /// Pair-major, `(M_b, M_p * (slots_pair + 1))` per class, already scaled by `sqrt|factor|`.
    std::vector<einsums::RuntimeTensor<double>> S_cls;
    /// Partner-major, `(M_p, M_b, slots_partner)` per class, carrying `sqrt|factor|` from the copy it was lifted from and the sign of its
    /// own.
    std::vector<einsums::RuntimeTensor<double>> S_T;
};

/// Each UPPER pair's truncated, canonical PNO basis and truncation cost.
///
/// Every list is indexed by upper-pair ordinal, the order of the planner's
/// `i <= j` sweep. The lower triangle is deliberately absent: `K_ji` is
/// `K_ij^T` and the shared quantities are shared objects, so the mirror is
/// the caller's host-side scatter, not arithmetic worth crossing a boundary.
///
/// `close` on the tensors and truncation energies because the two backends
/// reach them through different orderings of the same GEMMs; `exact` on the
/// PNO counts because a truncation decision that moves by one is a real
/// disagreement, not rounding.
///
/// Mirrors `dlpno.contracts.PnoTransform`, field for field.
struct PnoTransform {
    /// `(keep, keep)` exchange block in the canonical PNO basis.
    std::vector<einsums::RuntimeTensor<double>> K_pno;
    /// `(keep, keep)` amplitude block in the canonical PNO basis.
    std::vector<einsums::RuntimeTensor<double>> T_pno;
    /// `(npao_dom, keep)`: PAO domain -> canonical PNO, in one transform.
    std::vector<einsums::RuntimeTensor<double>> X_pno;
    /// `(keep,)` canonical PNO orbital energies.
    std::vector<einsums::RuntimeTensor<double>> e_pno;
    /// Surviving PNO count; the truncation decision itself.
    std::vector<std::int64_t> n_pno;
    /// The four graph-written pair-energy dots the truncation correction is built from, as the scalar tensors the dot ops wrote. Tensors
    /// rather than floats because the contract vocabulary forbids computed-float outputs - a captured stage returns before its graph
    /// executes - so the caller reads them after run() and forms `de = initial - trunc`.
    std::vector<einsums::RuntimeTensor<double>> e_initial;
    std::vector<einsums::RuntimeTensor<double>> e_os_initial;
    std::vector<einsums::RuntimeTensor<double>> e_trunc;
    std::vector<einsums::RuntimeTensor<double>> e_os_trunc;
};

/// One chunk of pairs' worth of PNO-basis integral blocks.
///
/// Every list is indexed by the pair's position in the chunk the planner
/// handed the stage, which is why they are all declared parallel: eleven of
/// them are read with one ordinal in the caller's scatter loop, and a short one
/// would be a silent out-of-bounds read.
///
/// **A block a pair does not have is a zero-extent tensor, not a missing
/// entry.** psi4 and the port both skip the density-fitted families on weak
/// pairs and store the pair-symmetric blocks once for `i <= j`, so a good
/// third of the entries here are legitimately absent. The alternative - short
/// lists plus a running counter per family - was tried first and is the shape
/// of an off-by-one that produces plausible integrals for the WRONG pair. A
/// zero-extent placeholder keeps every family indexable by the same ordinal
/// and costs a tensor header. The caller turns them back into the `None` its
/// consumers expect, using the same strong and diagonal flags the stage got.
///
/// `close` on everything tensor-valued because that is the contract's
/// promise; in practice both backends emit the same operations on the same
/// values and agree bit for bit, which is what `check_backends.py` asserts.
///
/// Mirrors `dlpno.contracts.PnoIntegralBlocks`, field for field.
///
/// The Python contract declares `K_mibj`, `J_ijmb`, `K_ivvv`, `K_mjai`, `K_jvvv`, `i_Qk`, `i_Qa`, `j_Qk`, `j_Qa`, `Qma`, `Qab` parallel:
/// always the same length, indexed by one ordinal. The caster checks it, because a short array here is a silent out-of-bounds read rather
/// than an exception.
struct PnoIntegralBlocks {
    /// `(m i | b j)`, `(nlmo_ij, npno_ij)`.
    std::vector<einsums::RuntimeTensor<double>> K_mibj;
    /// `(i j | m b)`, `(nlmo_ij, npno_ij)`. Shared with `ji` by the caller.
    std::vector<einsums::RuntimeTensor<double>> J_ijmb;
    /// `(i e | a f)` as rank 3 `(e, a, f)`. Never psi4's flattened form; see `dlpno.cc_integrals.PnoIntegrals`.
    std::vector<einsums::RuntimeTensor<double>> K_ivvv;
    /// The `ji` partners of the two families that are not transposes of themselves: `(m j | a i)` and `(j e | a f)`. Zero-extent on the
    /// diagonal, where the pair is its own partner.
    std::vector<einsums::RuntimeTensor<double>> K_mjai;
    std::vector<einsums::RuntimeTensor<double>> K_jvvv;
    /// `B^Q_{i m}` and `B^Q_{i a}`, psi4's `i_Qk_ij` and `i_Qa_ij`.
    std::vector<einsums::RuntimeTensor<double>> i_Qk;
    std::vector<einsums::RuntimeTensor<double>> i_Qa;
    /// Their `ji` partners, `B^Q_{j m}` and `B^Q_{j a}`.
    std::vector<einsums::RuntimeTensor<double>> j_Qk;
    std::vector<einsums::RuntimeTensor<double>> j_Qa;
    /// `B^Q_{m a}` and `B^Q_{a b}`, rank 3 per auxiliary function, which is the axis every consumer loops over.
    std::vector<einsums::RuntimeTensor<double>> Qma;
    std::vector<einsums::RuntimeTensor<double>> Qab;
    /// `(i k | a_ij c_kj)` and `(i a_ij | k c_kj)`, flattened over (pair, neighbour slot) in the planner's order: the pair's slab starts at
    /// the prefix sum of the neighbour-slot counts, so slot `s` of pair `p` is at `offset(p) + s`. A pair with no neighbour blocks -
    /// anything weak - contributes no slots at all, and a dead slot a zero-extent tensor.
    std::vector<einsums::RuntimeTensor<double>> J_ikac;
    std::vector<einsums::RuntimeTensor<double>> K_iakc;
    /// The same two families for the `ji` pair, over its own neighbour list.
    std::vector<einsums::RuntimeTensor<double>> J_jkac;
    std::vector<einsums::RuntimeTensor<double>> K_jakc;
};

} // namespace dlpno
