//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from dlpno.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: e237cabbd94dd5016afbffb691ee5c7b

/// @file
/// The C++ backend of the `transform_pnos` stage.
///
/// The other half of the Python implementation in `dlpno.stages`. Both
/// implement the same contract, both are selectable at runtime, and they are
/// compared against each other rather than one being retired.

#pragma once

#include <Einsums/Tensor/RuntimeTensor.hpp>

#include <cstdint>
#include <dlpno/Contracts.hpp>
#include <vector>

namespace dlpno {

/// Build each upper pair's truncated, canonical PNO basis.
///
/// The second DLPNO phase to state a contract, and the widest so far:
/// fifteen parameters against the 32 fields of `self` the phase touched
/// before `plan_pno_transform` was split away. Everything domain-shaped
/// arrives deduplicated (one tensor per distinct domain plus per-pair
/// ordinals), which is the planner handing over the memo caches' sharing
/// rather than one copy per pair.
///
/// Promoted on the 2026-08-08 re-profile: capture EMISSION is 45-56% of the
/// phase - ~1,630 nodes across three graphs at ~8 us of Python per node -
/// which is the per-node cost a language change removes and nothing else
/// does. See DESIGN-hybrid-framework.md, M6 step 3.
///
/// @param q_ia      Three-index integrals `(Q | i a)`, the full tensor.
/// @param fits      Per distinct domain block, `J^-1 (Q | i u)`, rank 3.
/// @param fit_of    Per upper pair, its index into `fits`.
/// @param fit_pos   Per upper pair, LMO `i`'s slot on the fit's middle axis.
/// @param dom_X     Per distinct PAO domain, the orthocanonicalizer.
/// @param dom_e     Per distinct PAO domain, the canonical orbital energies.
/// @param dom_F     Per distinct PAO domain, the canonical-basis Fock matrix.
/// @param dom_of    Per upper pair, its index into the `dom_*` lists.
/// @param ribfs     Per upper pair, the auxiliary indices of its fit domain.
/// @param paos      Per upper pair, the PAO indices its domain covers.
/// @param lmo_j     Per upper pair, LMO `j` for the `(Q | j a)` gather.
/// @param shift     Per upper pair, `F_ii + F_jj`.
/// @param pno_scale Per upper pair, the core-pair scaling on `T_CUT_PNO`.
/// @param min_pnos  Pairs keep at least this many PNOs, domain size permitting.
/// @param t_cut_pno The occupation-number cutoff.
[[nodiscard]] PnoTransform
transform_pnos(einsums::RuntimeTensor<double> const &q_ia, std::vector<einsums::RuntimeTensor<double>> const &fits,
               std::vector<std::int64_t> const &fit_of, std::vector<std::int64_t> const &fit_pos,
               std::vector<einsums::RuntimeTensor<double>> const &dom_X, std::vector<einsums::RuntimeTensor<double>> const &dom_e,
               std::vector<einsums::RuntimeTensor<double>> const &dom_F, std::vector<std::int64_t> const &dom_of,
               std::vector<std::vector<std::int64_t>> const &ribfs, std::vector<std::vector<std::int64_t>> const &paos,
               std::vector<std::int64_t> const &lmo_j, std::vector<double> const &shift, std::vector<double> const &pno_scale,
               std::int64_t min_pnos, double t_cut_pno);

} // namespace dlpno
