#!/usr/bin/env python3
# ----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# ----------------------------------------------------------------------------------------------

"""Aggregate per-module .pyi fragments into per-submodule stub files.

Each codegen invocation emits a single .pyi covering one Einsums module.
Inside, entities are grouped under ``# %%submodule: <name>`` sentinels —
empty name means top-level (binds into ``einsums._core``).

This script merges every fragment in --frag-dir into the einsums package
layout under --pkg-dir:

    einsums/_core.pyi      ← top-level entities
    einsums/<submodule>.pyi ← per-submodule entities (e.g. linalg, graph)
    einsums/__init__.pyi   ← re-exports + py.typed marker
    einsums/py.typed       ← PEP 561 marker

Imports are deduplicated; the script writes a single shared header at
the top of each output file. Empty submodules are skipped.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Sentinel that groups entities by submodule inside a fragment.
SENTINEL = re.compile(r"^# %%submodule: (.*)$")

# The header block PyiEmitter writes; matched literally so we can strip
# it from each fragment and emit one shared header per output file.
HEADER_PREFIX = "from __future__ import annotations\n"

SHARED_HEADER = """\
# Auto-generated by einsums-pybind. Do not edit.
# pyright: reportInvalidTypeForm=false

from __future__ import annotations
from typing import Any, Literal, overload
from collections.abc import Callable
import enum
import numpy
import numpy.typing

"""


def parse_fragment(path: Path) -> dict[str, str]:
    """Return {submodule_name: body} for each ``# %%submodule:`` block."""
    text = path.read_text()
    blocks: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines(keepends=True):
        m = SENTINEL.match(line.rstrip("\n"))
        if m is not None:
            current = m.group(1)
            blocks.setdefault(current, [])
            continue
        if current is None:
            # Lines before the first sentinel are the per-fragment
            # header (imports, banner). Discarded — we emit one shared
            # header per output.
            continue
        blocks[current].append(line)
    return {sm: "".join(lines).rstrip() + "\n" for sm, lines in blocks.items() if lines}


def aggregate(frag_dir: Path, pkg_dir: Path) -> dict[str, Path]:
    """Read every *.pyi in `frag_dir` and write per-submodule files into `pkg_dir`."""
    by_sub: dict[str, list[str]] = {}
    for frag in sorted(frag_dir.glob("*.pyi")):
        for sub, body in parse_fragment(frag).items():
            by_sub.setdefault(sub, []).append(f"# from: {frag.name}\n{body}")

    pkg_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for sub, parts in by_sub.items():
        out_name = "_core.pyi" if sub == "" else f"{sub}.pyi"
        out_path = pkg_dir / out_name
        out_path.write_text(SHARED_HEADER + "\n".join(parts).rstrip() + "\n")
        written[sub] = out_path

    # PEP 561: empty marker file telling type-checkers this package
    # ships its own stubs.
    (pkg_dir / "py.typed").write_text("")

    # __init__.pyi: re-export everything from _core so ``import einsums``
    # gives pyright the full top-level surface.
    init_pyi = pkg_dir / "__init__.pyi"
    init_pyi.write_text(SHARED_HEADER + "from einsums._core import *  # noqa: F401,F403\n")

    return written


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--frag-dir", required=True, type=Path,
                   help="Directory containing per-module .pyi fragments.")
    p.add_argument("--pkg-dir", required=True, type=Path,
                   help="Destination einsums/ package directory.")
    args = p.parse_args(argv)

    if not args.frag_dir.is_dir():
        print(f"aggregate_stubs: {args.frag_dir} is not a directory", file=sys.stderr)
        return 1

    written = aggregate(args.frag_dir, args.pkg_dir)
    if written:
        names = ", ".join(sorted(p.name for p in written.values()))
        print(f"aggregate_stubs: wrote {names} to {args.pkg_dir}")
    else:
        print("aggregate_stubs: no .pyi fragments found", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
