//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from hybrid_mp2.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: d28898df0d558d6fcd18e22b7bedcf23

/// @file
/// Cross-boundary contract aggregates for the hybrid_mp2 stages.
///
/// One struct per `@contract` dataclass reachable from `hybrid_mp2.stages`,
/// field for field. That correspondence IS the contract; it is what
/// `python -m einsums.stages check` verifies, and it is why this file is
/// generated rather than written. The prose below is carried across from the
/// Python `#:` comments and docstrings, so the rationale lives in one place
/// and cannot be lost by regenerating this header.

#pragma once

#include <Einsums/Tensor/RuntimeTensor.hpp>

namespace hybrid_mp2 {

/// What the MP2 numerics stage produces.
///
/// Both fields are length-1 tensors rather than floats, and that is a rule
/// worth internalizing before writing your own contract: a captured stage
/// returns before its graphs execute, so a computed `float` output would be
/// read too early, and the contract validator refuses it. The stage writes
/// its reductions into scalar tensors instead, and the caller reads them
/// after the stage has run.
///
/// Mirrors `hybrid_mp2.contracts.Mp2Energy`, field for field.
struct Mp2Energy {
    /// Total MP2 correlation energy, as a graph-written scalar tensor.
    einsums::RuntimeTensor<double> e_corr;
    /// Opposite-spin component; same-spin is `e_corr - e_os`, subtracted by the caller host-side.
    einsums::RuntimeTensor<double> e_os;
};

} // namespace hybrid_mp2
