//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from hybrid_mp2.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: 8fa057ba7d0571adbdf3cb67341e4367

/// @file
/// The C++ backend of the `mp2_energy` stage.
///
/// The other half of the Python implementation in `hybrid_mp2.stages`. Both
/// implement the same contract, both are selectable at runtime, and they are
/// compared against each other rather than one being retired.

#pragma once

#include <Einsums/Tensor/RuntimeTensor.hpp>

#include <hybrid_mp2/Contracts.hpp>

namespace hybrid_mp2 {

/// RHF MP2 correlation energy from MO `(ia|jb)` integrals.
///
/// Pair-driven over `i <= j`: one captured graph over the pair loop,
/// replayed as an OpenMP team. `eager` because the stage runs its own
/// graph to completion rather than emitting into an ambient capture, which
/// the session reports as a graph split.
///
/// @param iajb    Chemists' `(ia|jb)`, shape `(nocc, nvir, nocc, nvir)`.
/// @param eps_occ Active occupied orbital energies, shape `(nocc,)`.
/// @param eps_vir Active virtual orbital energies, shape `(nvir,)`.
[[nodiscard]] Mp2Energy mp2_energy(einsums::RuntimeTensor<double> const &iajb, einsums::RuntimeTensor<double> const &eps_occ,
                                   einsums::RuntimeTensor<double> const &eps_vir);

} // namespace hybrid_mp2
