#!/usr/bin/env python3
# ----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
# ----------------------------------------------------------------------------------------------
"""Generate the command-line argument reference from the option descriptors.

The page is joined from two inputs, because neither one can produce it alone:

* The C++ descriptors in ``libs/Einsums/<Module>/include/Einsums/<Module>/Options.hpp``
  say which options exist, what category each groups under, and how each is
  invoked, placeholder included. That is the half that used to drift: the page
  once documented two options no build ever registered and missed most of the
  ones it did.
* ``docs/sphinx/user/arguments.yaml`` says what each option means and when it
  changed. That is the half a generator cannot invent: a bullet list of log
  levels, a cross-reference into the C++ API, a paragraph explaining that an
  option deliberately runs the slower form.

Both halves are checked against each other. A sidecar entry for an option no
descriptor declares fails, and so does a descriptor with no sidecar entry, which
is the point: adding an option without documenting it breaks the build rather
than quietly shipping an incomplete page.

Usage::

    generate_arguments_rst.py --docs-json <a.cppdocs.json> [...] \
                              --template arguments.rst.in \
                              --sidecar arguments.yaml --output arguments.rst
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# docs/tools -> the repository root, where the shared descriptor extractor
# lives, shared with the generator for einsums/rc.py. The generator runs from
# the build tree with no package installed, so the path is relative to this
# file rather than to a working directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "devtools"))

import option_descriptors as od  # noqa: E402

try:
    import yaml
except ImportError:  # pragma: no cover - the env declares pyyaml
    od.die("pyyaml is required to build the documentation (conda install pyyaml)")

# The order the categories read in, and the heading each gets. A descriptor's
# category is a ``--help`` grouping, chosen for the terse listing there;
# the manual wants both a different order (what a reader reaches for first,
# not alphabetical) and room for a fuller title.
#
# A category missing from this list is not dropped - it renders last, under its
# own name - so a new module's options reach the page whether or not anyone
# remembers to come back here.
CATEGORY_ORDER = (
    ("Buffer Allocator", "Basic Arguments"),
    ("Logging", "Logging"),
    ("Profile", "Profiling"),
    ("ComputeGraph Passes", "ComputeGraph Pass Options"),
    ("Hardware", "Hardware Profile"),
    ("GPU", "GPU"),
    ("HPTT", "HPTT"),
    ("Tensor Options", "Tensor Storage"),
    ("Debug", "Advanced Arguments"),
)

# Any ``--einsums:...`` spelling a body names, so it can be held against the
# registry. Backticks and whitespace end the match, so ``--einsums:pass:disable
# CSE,Reorder`` yields just the option.
_OPTION_MENTION = re.compile(r"--einsums:[A-Za-z0-9_:-]+")

_BODY_INDENT = "    "


def section(title: str) -> str:
    """A section heading, overlined and underlined as the manual writes them."""
    rule = "=" * len(title)
    return f"{rule}\n{title}\n{rule}"


def indent(text: str, prefix: str) -> str:
    return "\n".join(prefix + line if line.strip() else "" for line in text.split("\n"))


def known_spellings(options: list[dict]) -> set[str]:
    """Every option name a page may name, negations included.

    A flag's ``no-`` spelling is generated by registration rather than declared,
    so it exists on the command line without appearing in any descriptor. It is
    still a name the page is allowed to print - and the one spelling that went
    wrong here before, when the page advertised ``--einsums:profiler:no-append``
    for an option registered as ``einsums:profile:append``.
    """
    spellings = set()
    for opt in options:
        spellings.add(f"--{opt['name']}")
        if opt["kind"] == "flag":
            spellings.add(f"--{od.negated_name(opt['name'])}")
    return spellings


def check_mentions(text: str, spellings: set[str]) -> list[str]:
    """Option spellings in `text` that no registered option answers to."""
    return sorted({m for m in _OPTION_MENTION.findall(text) if m not in spellings})


def ordered_categories(options: list[dict]) -> list[tuple[str, list[dict]]]:
    """Categories in reading order, each with its options in declaration order.

    Declaration order is the module author's grouping - the crash handler beside
    the directory its dumps go in - and is stable, because the headers are
    handed to the parser in a sorted order.
    """
    groups: dict[str, list[dict]] = {}
    for opt in options:
        groups.setdefault(opt["category"], []).append(opt)

    titles = dict(CATEGORY_ORDER)
    ordered = [c for c, _ in CATEGORY_ORDER if c in groups]
    ordered += sorted(c for c in groups if c not in titles)
    return [(titles.get(c, c), groups[c]) for c in ordered]


def render_option(opt: dict, entry: dict) -> str:
    """One ``.. option::`` block: descriptor invocation, sidecar prose, history."""
    lines = [f".. option:: {od.invocation(opt)}", ""]

    body = (entry.get("body") or "").strip("\n")
    if not body:
        od.die(f"option {opt['name']} has an empty body in the sidecar")
    lines.append(indent(body, _BODY_INDENT))
    lines.append("")

    history = [f"{_BODY_INDENT}.. versionadded:: {entry['added']}"]
    added_text = (entry.get("added_text") or "").strip("\n")
    if added_text:
        history.append(indent(added_text, _BODY_INDENT * 2))
    for change in entry.get("changed") or []:
        history.append(f"{_BODY_INDENT}.. versionchanged:: {change['version']}")
        history.append(indent(change["text"].strip("\n"), _BODY_INDENT * 2))
    lines.extend(history)
    return "\n".join(lines)


def render_options(options: list[dict], sidecar: dict) -> str:
    blocks = []
    for title, opts in ordered_categories(options):
        blocks.append(section(title))
        blocks.append("")
        for opt in opts:
            blocks.append(render_option(opt, sidecar[opt["name"]]))
            blocks.append("")
    return "\n".join(blocks).rstrip("\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--docs-json", type=Path, nargs="+", required=True,
                    help="apiary C++ docs JSON for the Options.hpp headers")
    ap.add_argument("--template", type=Path, required=True, help="arguments.rst.in")
    ap.add_argument("--sidecar", type=Path, required=True, help="arguments.yaml")
    ap.add_argument("--output", type=Path, required=True, help="the arguments.rst to write")
    args = ap.parse_args()

    options = od.collect_options(od.load_docs(args.docs_json))

    try:
        sidecar = yaml.safe_load(args.sidecar.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        od.die(f"cannot read {args.sidecar}: {exc}")
    if not isinstance(sidecar, dict):
        od.die(f"{args.sidecar} must be a mapping of option name to entry")

    # The two halves must cover exactly the same options. Documenting an option
    # that no longer exists is a stale page; declaring one nobody documented is
    # the failure this generator exists to make impossible.
    declared = {opt["name"] for opt in options}
    documented = set(sidecar)
    if documented - declared:
        od.die(f"{args.sidecar} documents option(s) no descriptor declares: "
               f"{', '.join(sorted(documented - declared))}")
    if declared - documented:
        od.die(f"option(s) declared with no entry in {args.sidecar}: "
               f"{', '.join(sorted(declared - documented))} - every option needs documenting")

    for name, entry in sidecar.items():
        if not isinstance(entry, dict) or not entry.get("added"):
            od.die(f"{args.sidecar}: entry for {name} needs at least an 'added' version and a 'body'")

    template = args.template.read_text(encoding="utf-8")
    if "@OPTIONS@" not in template:
        od.die(f"{args.template} has no @OPTIONS@ placeholder")

    # Every option spelling the page prints, in the preamble and in the bodies,
    # has to be one the registry answers to. Version history is deliberately
    # exempt: it is where a name that no longer parses belongs.
    spellings = known_spellings(options)
    unknown: dict[str, list[str]] = {}
    for where, text in [(str(args.template), template)] + \
                       [(name, entry.get("body") or "") for name, entry in sidecar.items()]:
        bad = check_mentions(text, spellings)
        if bad:
            unknown[where] = bad
    if unknown:
        detail = "; ".join(f"{where} names {', '.join(bad)}" for where, bad in unknown.items())
        od.die(f"option spelling(s) no option registers: {detail}")

    text = template.replace("@OPTIONS@", render_options(options, sidecar))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Written only on change, so a no-op regeneration does not restamp the file
    # and cost Sphinx a re-read of the page.
    if not args.output.is_file() or args.output.read_text(encoding="utf-8") != text:
        args.output.write_text(text, encoding="utf-8")
    print(f"generate_arguments_rst: {len(options)} option(s) -> {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
