//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

/// @file
/// How every einsums namespace block is opened and closed.
///
/// The library lives in `einsums::inline vN`, N the ABI generation: invisible to lookup, but in
/// the mangled names, so incompatible copies cannot answer for each other.
///
/// Write namespace blocks through these macros rather than by hand:
///
/// @code
///     EINSUMS_NAMESPACE_BEGIN(compute_graph::passes)
///     class MemoryPlanning final : public OptimizerPass { ... };
///     EINSUMS_NAMESPACE_END(compute_graph::passes)
///
///     EINSUMS_NAMESPACE_BEGIN()
///     class Tensor { ... };
///     EINSUMS_NAMESPACE_END()
/// @endcode
///
/// The sub-namespace is an argument because most blocks are nested. A depth mismatch between BEGIN
/// and END fails to compile; an argument mismatch does not, and CI checks for it.

#pragma once

#include <Einsums/Config/Defines.hpp>

#if !defined(EINSUMS_ABI_TAG)
#    error "EINSUMS_ABI_TAG is missing; <Einsums/Config/Defines.hpp> is generated by CMake"
#endif

// clang-format off
// clang-format would split the unbalanced braces in __VA_OPT__ across lines.

/// Open `einsums::inline <abi tag>`, optionally descending into a
/// sub-namespace path such as `compute_graph::passes`.
#define EINSUMS_NAMESPACE_BEGIN(...)                                           \
    namespace einsums {                                                        \
    inline namespace EINSUMS_ABI_TAG {                                         \
    __VA_OPT__(namespace __VA_ARGS__ {)

/// Close a block opened by EINSUMS_NAMESPACE_BEGIN. Pass the same path.
#define EINSUMS_NAMESPACE_END(...)                                             \
    __VA_OPT__(})                                                              \
    }                                                                          \
    }
// clang-format on
