#----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#----------------------------------------------------------------------------------------------

"""Render the C++ side of a stages module, and write it without losing edits.

Generated files come in two kinds and they are treated differently on purpose.

**Regenerated** files - the contract aggregates, the stage headers, the
casters, the bindings - are rewritten on every run and carry a hash of what
``promote`` last wrote. A file whose content no longer matches its hash is one
a human edited, and ``promote`` refuses it rather than discarding the edit.
Without that, the first person to add a helper declaration to a generated
header loses it on the next run with no way to know why.

**Scaffolded** files - the build file, the port skeleton, the differential test
- are written once and then belong to the developer. They carry a banner saying
so and no hash: a hash on a file nobody will ever rewrite is a number that goes
stale immediately and trains people to ignore banners.

Output is passed through ``clang-format`` and ``cmake-format`` when they are on
PATH, configured from the OUTPUT path so the developer's own project style
governs. That is not cosmetic. Generated code lands in a tree with a formatting
hook, the hook reformats it, and the reformatted file no longer matches its
hash - so the next ``promote`` refuses to touch a file nobody edited.
Formatting here closes that loop.

The banner goes on after formatting, not before, so a formatter can never
rewrite the hash line it is being checked against.
"""

import dataclasses as _dataclasses
import hashlib as _hashlib
import pathlib as _pathlib
import re as _re
import shutil as _shutil
import subprocess as _subprocess

from ._promote import PromoteError, contract_includes, cpp_string_literal

__all__ = ["Written", "Emitter", "Formatters", "find_formatters", "generate", "is_sealed"]

#: Deliberately short lines, and a truncated digest. The banner is a comment,
#: and a formatter reflows any comment line past its column limit - which would
#: rewrite the hash line and make the next run refuse a file nobody touched. 32
#: hex characters keep it to 49 columns, under every style anyone sets.
_HASH_WIDTH = 32
_HASH_RE = _re.compile(r"^(?://|#) promote-hash: [0-9a-f]{%d}$" % _HASH_WIDTH, _re.M)
_PLACEHOLDER = "0" * _HASH_WIDTH

_GENERATED_NOTE = (
    "Generated by 'python -m einsums.stages promote' from {source}.",
    "Edits are lost on the next run; change the Python contract instead.",
)
_SCAFFOLD_NOTE = (
    "Scaffolded by 'python -m einsums.stages promote' from {source}.",
    "Written once and never overwritten: this file is yours.",
)
#: cmake-format rewraps a comment block as a paragraph, joining short lines
#: rather than only breaking long ones the way clang-format does. A two-line
#: banner in a CMakeLists is therefore not a fixed point, and the difference
#: shows up as a spurious diff the first time a hook runs. One short line is.
_SCAFFOLD_NOTE_ONE_LINE = ("Scaffolded once by 'python -m einsums.stages promote'; this file is yours.",)


# ----------------------------------------------------------------------
# Banners, hashing, writing
# ----------------------------------------------------------------------
def _comment(lines, prefix: str) -> str:
    return "\n".join(f"{prefix} {line}".rstrip() for line in lines)


def _banner(source: str, *, prefix: str, regenerated: bool, license_text: str | None) -> str:
    rule = prefix + "-" * 94
    parts = []
    if license_text:
        body = [line.rstrip() for line in license_text.strip("\n").split("\n")]
        parts.append("\n".join([rule, _comment(body, prefix), rule]))
    if regenerated:
        note = _GENERATED_NOTE
    else:
        note = _SCAFFOLD_NOTE if prefix == "//" else _SCAFFOLD_NOTE_ONE_LINE
    lines = [line.format(source=source) for line in note]
    if regenerated:
        lines.append(f"promote-hash: {_PLACEHOLDER}")
    parts.append(_comment(lines, prefix))
    return "\n\n".join(parts)


def _digest(text: str) -> str:
    """The hash of everything except the hash line itself.

    Blanking the line rather than deleting it keeps the two sides of the
    comparison literally the same operation: seal and verify both hash the file
    with that one line emptied, so any edit anywhere else moves the digest.
    """
    return _hashlib.sha256(_HASH_RE.sub("", text, count=1).encode()).hexdigest()


def _seal(text: str, prefix: str) -> str:
    """Replace the placeholder hash with the digest of everything else."""
    digest = _digest(text)[:_HASH_WIDTH]
    return _HASH_RE.sub(lambda _: f"{prefix} promote-hash: {digest}", text, count=1)


def is_sealed(text: str) -> bool:
    """Whether *text* still matches the hash ``promote`` sealed it with."""
    match = _HASH_RE.search(text)
    if match is None:
        return False
    return _digest(text)[:_HASH_WIDTH] == match.group(0).rsplit(": ", 1)[1]


@_dataclasses.dataclass(frozen=True)
class Written:
    """What happened to one output file."""

    path: _pathlib.Path
    #: created, updated, unchanged, kept (scaffold already present), or refused.
    action: str
    detail: str = ""

    @property
    def refused(self) -> bool:
        return self.action == "refused"


_CMAKE_FORMAT_CONFIGS = (
    ".cmake-format.py",
    ".cmake-format.yaml",
    ".cmake-format.json",
    ".cmake-format",
    "cmake-format.py",
    "cmake-format.yaml",
)


def _cmake_format_config(path: _pathlib.Path):
    """The cmake-format config governing *path*, found the way the tool does.

    Passed explicitly rather than relied on, because the config is discovered
    from the file's own directory and this runs with the file not yet written.
    """
    for directory in [path.parent.resolve(), *path.parent.resolve().parents]:
        for name in _CMAKE_FORMAT_CONFIGS:
            candidate = directory / name
            if candidate.is_file():
                return candidate
    return None


def _run_formatter(argv, text: str, path: _pathlib.Path, tool: str) -> str:
    try:
        done = _subprocess.run(argv, input=text, capture_output=True, text=True, check=True)
    except (OSError, _subprocess.CalledProcessError) as exc:
        stderr = getattr(exc, "stderr", "") or str(exc)
        raise PromoteError(
            f"{path}: {tool} failed, so the generated file would not survive a formatting "
            f"hook: {stderr.strip()}"
        ) from exc

    # A formatter that exits 0 and returns nothing has happened here: with a
    # config file and no -o, cmake-format writes to a default output and leaves
    # stdout empty. The result was a CMakeLists.txt containing its banner and
    # not one command, which configured cleanly and produced a build with no
    # target in it. Formatting never halves a file, so anything near that is a
    # tool being driven wrong rather than a style opinion.
    if len(done.stdout.strip()) < len(text.strip()) // 2:
        raise PromoteError(
            f"{path}: {tool} returned {len(done.stdout)} characters for {len(text)} of input, "
            f"which is not formatting. Check how it is being invoked before trusting any file "
            f"it has already written."
        )
    return done.stdout


def _format(text: str, path: _pathlib.Path, tools) -> str:
    """Format a generated body with whichever tool owns that file type."""
    if path.suffix in (".hpp", ".cpp") and tools.clang_format:
        return _run_formatter(
            [
                tools.clang_format,
                "--style=file",
                "--fallback-style=LLVM",
                f"--assume-filename={path}",
            ],
            text,
            path,
            "clang-format",
        )
    if path.name == "CMakeLists.txt" and tools.cmake_format:
        # Argument order matters twice over. -c takes nargs="+", so it must not
        # be the last option before the "-" input or it swallows it; and -o -
        # is not optional, because with a config file and no explicit output
        # cmake-format exits 0 having written nothing to stdout.
        argv = [tools.cmake_format]
        config = _cmake_format_config(path)
        if config is not None:
            argv += ["-c", str(config)]
        return _run_formatter(argv + ["-o", "-", "-"], text, path, "cmake-format")
    return text


# ----------------------------------------------------------------------
# The emitter
# ----------------------------------------------------------------------
class Emitter:
    """Renders a :class:`~einsums.stages._promote.ModuleModel` into a directory."""

    def __init__(
        self,
        model,
        out_dir,
        *,
        license_text: str | None = None,
        formatters=None,
        force: bool = False,
        dry_run: bool = False,
        skeletons=None,
    ):
        self.model = model
        self.out = _pathlib.Path(out_dir)
        self.license_text = license_text
        self.formatters = formatters if formatters is not None else Formatters(None, None)
        self.force = force
        self.dry_run = dry_run
        #: Which stages get a port skeleton and a differential test. None means
        #: all of them; a name on the command line filters THIS and nothing
        #: else, since the generated module always covers every stage.
        self.skeletons = skeletons
        self.results: list[Written] = []

    # -- file plumbing --------------------------------------------------
    def _write(self, rel: str, text: str, *, regenerated: bool) -> Written:
        path = self.out / rel
        existing = path.read_text() if path.exists() else None
        if existing is not None and not regenerated:
            # A scaffold that is already there is the developer's file now, and
            # the port lives in one of these. Nothing below may run.
            result = Written(path, "kept")
            self.results.append(result)
            return result

        prefix = "#" if path.suffix in (".txt", ".py", ".cmake") else "//"
        banner = _banner(
            self.model.source_module,
            prefix=prefix,
            regenerated=regenerated,
            license_text=self.license_text,
        )
        # The banner goes on AFTER formatting. clang-format reflows any comment
        # past the column limit, and the one comment it must never rewrite is
        # the hash line: a reflowed banner makes the next run refuse a file
        # nobody edited. Formatting only the body puts it out of reach.
        body = _format(text.lstrip("\n"), path, self.formatters)
        text = f"{banner}\n\n{body}"
        if not text.endswith("\n"):
            text += "\n"
        if regenerated:
            text = _seal(text, prefix)

        if existing is None:
            result = Written(path, "created")
        elif existing == text:
            result = Written(path, "unchanged")
        elif not is_sealed(existing) and not self.force:
            result = Written(
                path,
                "refused",
                "edited by hand since promote last wrote it. Move the change into the Python "
                "contract, or pass --force to discard it.",
            )
        else:
            result = Written(path, "updated")

        if result.action in ("created", "updated") and not self.dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        self.results.append(result)
        return result

    # -- rendering ------------------------------------------------------
    def run(self) -> list[Written]:
        m = self.model
        inc = f"include/{m.namespace}"
        self._write(f"{inc}/Contracts.hpp", self._contracts_hpp(), regenerated=True)
        for st in m.stages:
            self._write(f"{inc}/{st.unit}.hpp", self._stage_hpp(st), regenerated=True)
        if m.argument_contracts:
            self._write(f"{inc}/Casters.hpp", self._casters_hpp(), regenerated=True)
        self._write("bindings.cpp", self._bindings_cpp(), regenerated=True)
        self._write("CMakeLists.txt", self._cmakelists(), regenerated=False)
        for st in m.stages:
            if self.skeletons is not None and st.name not in self.skeletons:
                continue
            self._write(f"src/{st.unit}.cpp", self._skeleton_cpp(st), regenerated=False)
            self._write(f"tests/test_diff_{st.name}.py", self._diff_test(st), regenerated=False)
        return self.results

    # -- include blocks -------------------------------------------------
    @staticmethod
    def _includes(names) -> str:
        einsums = sorted(n for n in names if n.startswith("Einsums/"))
        other = sorted(n for n in names if not n.startswith("Einsums/"))
        blocks = []
        if einsums:
            blocks.append("\n".join(f"#include <{n}>" for n in einsums))
        if other:
            blocks.append("\n".join(f"#include <{n}>" for n in other))
        return "\n\n".join(blocks)

    @staticmethod
    def _doc(lines, indent: str = "") -> str:
        return "\n".join(f"{indent}///{' ' + line if line else ''}".rstrip() for line in lines)

    # -- Contracts.hpp --------------------------------------------------
    def _contracts_hpp(self) -> str:
        m = self.model
        includes: frozenset = frozenset()
        for c in m.contracts:
            includes |= contract_includes(c)

        structs = []
        for c in m.contracts:
            doc = list(c.doc)
            doc.append("")
            doc.append(f"Mirrors `{c.py_type.__module__}.{c.name}`, field for field.")
            for group in c.parallel:
                doc.append("")
                doc.append(
                    "The Python contract declares " + ", ".join(f"`{n}`" for n in group) + " parallel: "
                    "always the same length, indexed by one ordinal. The caster checks it, because "
                    "a short array here is a silent out-of-bounds read rather than an exception."
                )
            body = []
            for f in c.fields:
                if f.doc:
                    body.append(self._doc(f.doc, "    "))
                body.append(f"    {f.cpp} {f.name};")
            structs.append(f"{self._doc(doc)}\nstruct {c.name} {{\n" + "\n".join(body) + "\n};")

        return f"""
/// @file
/// Cross-boundary contract aggregates for the {m.namespace} stages.
///
/// One struct per `@contract` dataclass reachable from `{m.source_module}`,
/// field for field. That correspondence IS the contract; it is what
/// `python -m einsums.stages check` verifies, and it is why this file is
/// generated rather than written. The prose below is carried across from the
/// Python `#:` comments and docstrings, so the rationale lives in one place
/// and cannot be lost by regenerating this header.

#pragma once

{self._includes(includes)}

namespace {m.namespace} {{

{chr(10).join(chr(10).join([s, ""]) for s in structs).rstrip()}

}} // namespace {m.namespace}
"""

    # -- <Stage>.hpp ----------------------------------------------------
    def _stage_hpp(self, st) -> str:
        m = self.model
        includes = set(st.includes) | {f"{m.namespace}/Contracts.hpp"}
        doc = [st.summary] if st.summary else []
        if st.doc:
            doc.extend(["", *st.doc])
        params_doc = [p for p in st.params if p.doc]
        if params_doc:
            doc.append("")
            width = max(len(p.name) for p in params_doc)
            for p in params_doc:
                head, *rest = p.doc
                doc.append(f"@param {p.name.ljust(width)} {head}")
                doc.extend(f"       {' ' * width} {line}" for line in rest)

        nodiscard = "" if st.return_cpp == "void" else "[[nodiscard]] "
        params = ", ".join(p.decl_with_default for p in st.params)
        return f"""
/// @file
/// The C++ backend of the `{st.name}` stage.
///
/// The other half of the Python implementation in `{m.source_module}`. Both
/// implement the same contract, both are selectable at runtime, and they are
/// compared against each other rather than one being retired.

#pragma once

{self._includes(includes)}

namespace {m.namespace} {{

{self._doc(doc)}
{nodiscard}{st.return_cpp} {st.name}({params});

}} // namespace {m.namespace}
"""

    # -- Casters.hpp ----------------------------------------------------
    def _casters_hpp(self) -> str:
        m = self.model
        casters = []
        for c in m.argument_contracts:
            reads = "\n".join(
                f'        read_field(src, c, "{f.name}", value.{f.name});' for f in c.fields
            )
            checks = ""
            for group in c.parallel:
                head, *rest = group
                entries = ", ".join(
                    f'std::pair{{"{n}", value.{n}.size()}}' for n in rest
                )
                checks += f"""
        // Declared parallel by the Python contract. Checked here because every
        // loop over the group indexes all of its arrays with one ordinal, so a
        // short one is a silent out-of-bounds read rather than an exception.
        auto const n_{head} = value.{head}.size();
        for (auto const &[name, size] : {{{entries}}}) {{
            if (size != n_{head}) {{
                throw value_error(std::string(c) + ": fields {', '.join(group)} must be parallel, but '{head}' has " +
                                  std::to_string(n_{head}) + " entries and '" + name + "' has " + std::to_string(size) + ".");
            }}
        }}
"""
            casters.append(
                f"""template <>
struct type_caster<{m.namespace}::{c.name}> {{
    PYBIND11_TYPE_CASTER({m.namespace}::{c.name}, const_name("{c.name}"));

    /// Python `@contract` dataclass -> the C++ aggregate.
    ///
    /// Throws rather than returning false. False is pybind's "try the next
    /// overload", and there is no next overload: it surfaces as a generic
    /// "incompatible function arguments" listing every parameter, which hides
    /// the one field that was actually wrong.
    bool load(handle src, bool) {{
        if (src.is_none()) {{
            return false;
        }}
        using {m.namespace}_detail::read_field;
        char const *c = "{c.name}";

{reads}
{checks}        return true;
    }}
}};"""
            )

        return f"""
/// @file
/// pybind11 casters for the {m.namespace} contract types.
///
/// One caster per `@contract` dataclass that a stage takes as an ARGUMENT.
/// With these included, a stage entry point is `m.def("stage_x", &{m.namespace}::x)`
/// and the conversion is invisible; the binding's signature is the C++ API
/// verbatim rather than a field-by-field read at every call site.
///
/// The direction is fixed, and the "obvious" improvement is the one wrong
/// answer. Python OWNS the contract: the planner builds a `@contract`
/// dataclass and this side reads it. Binding the aggregate to Python and
/// having the planner construct it instead would make the pure-Python path
/// require this module to exist, which breaks the promise that a method runs
/// all-Python before anyone writes C++. Reading a foreign object field by
/// field is the price of that, and it is paid once, here, instead of at every
/// entry point.
///
/// A returned contract is bound as a `py::class_` in `bindings.cpp` instead,
/// for the symmetric reason: a caster converts into C++ and cannot hand an
/// object back.
///
/// Cost note for whoever needs it later: `load()` copies each field into a
/// `std::vector`. For a stage called once per calculation that is not worth
/// avoiding. A stage taking a contract-shaped argument inside an iteration
/// loop would want the flat arrays to arrive as numpy buffers with the caster
/// holding spans instead - zero copy, at the cost of the C++ side no longer
/// owning its inputs. This is the only file that would change.

#pragma once

#include <{m.namespace}/Contracts.hpp>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <string>

namespace pybind11::detail {{

namespace {m.namespace}_detail {{

/// Read one field, and say which one when it is missing or the wrong shape.
///
/// A function rather than an inline `.cast<>()` because a bare cast failure
/// partway down a wide contract reports the C++ type it wanted and nothing
/// about where it was, which turns a five-second fix into a bisect.
template <typename T>
void read_field(handle src, char const *contract, char const *field, T &out) {{
    if (!hasattr(src, field)) {{
        throw value_error(std::string(contract) + ": object has no field '" + field +
                          "'. The C++ struct and the @contract dataclass have drifted apart.");
    }}
    try {{
        out = getattr(src, field).template cast<T>();
    }} catch (cast_error const &) {{
        throw value_error(std::string(contract) + "." + field + ": cannot convert to its C++ type. " +
                          "Check the field's element type against the contract.");
    }}
}}

}} // namespace {m.namespace}_detail

{(chr(10) * 2).join(casters)}

}} // namespace pybind11::detail
"""

    # -- bindings.cpp ---------------------------------------------------
    def _bindings_cpp(self) -> str:
        m = self.model
        includes = {"Einsums/Python/StageModule.hpp"}
        includes |= {f"{m.namespace}/{st.unit}.hpp" for st in m.stages}
        if m.argument_contracts:
            includes.add(f"{m.namespace}/Casters.hpp")
        includes |= {"pybind11/pybind11.h", "pybind11/stl.h"}

        classes = []
        for c in m.return_contracts:
            defs = "\n".join(
                f'        .def_readonly("{f.name}", &{m.namespace}::{c.name}::{f.name})'
                for f in c.fields
            )
            classes.append(
                f"    // Every access to a list-valued field converts the underlying\n"
                f"    // std::vector into a fresh Python list. A consumer that indexes\n"
                f"    // result.field[i] inside a loop is therefore quadratic in the list\n"
                f"    // length; read each field into a local once and index that.\n"
                f'    py::class_<{m.namespace}::{c.name}>(m, "{c.name}")\n{defs};'
            )

        entries = []
        for st in m.stages:
            args = "".join(
                f', py::arg("{p.name}")'
                + ("" if p.cpp_default is None else f" = {p.cpp_default}")
                for p in st.params
            )
            doc = f", {cpp_string_literal(st.summary)}" if st.summary else ""
            entries.append(
                f'    m.def("{st.entry_point}", &{m.namespace}::{st.name}{args}{doc});'
            )

        class_block = ""
        if classes:
            class_block = f"""
    // Returned contracts are real bound types. Argument-position contracts
    // cross through the casters in Casters.hpp instead, which is why they need
    // no class_ here: direction decides the mechanism.
{chr(10).join(classes)}
"""

        return f"""
/// @file
/// The {m.namespace} stage module: the handshake, and one entry point per stage.

{self._includes(includes)}

namespace py = pybind11;

PYBIND11_MODULE({m.module_name}, m) {{
    m.doc() = "C++ backends for the {m.namespace} stages.";

    // Must come first: einsums.stages.load_stage_module refuses to read
    // anything out of a module that has not registered against the same
    // libEinsums it is bound to.
    EINSUMS_STAGE_MODULE(m, "{m.module_name}");
{class_block}
    // The stage_ prefix is what load_stage_module scans for: the module states
    // which of its symbols are stages rather than leaving the loader to guess
    // from everything callable.
{chr(10).join(entries)}
}}
"""

    # -- CMakeLists.txt -------------------------------------------------
    def _cmakelists(self) -> str:
        m = self.model
        sources = " ".join(["bindings.cpp"] + [f"src/{st.unit}.cpp" for st in m.stages])
        return f"""
# An out-of-tree stage module, built against an INSTALLED Einsums:
#
#   cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release \\
#     "-DCMAKE_PREFIX_PATH=/path/to/einsums/install;$CONDA_PREFIX" \\
#     -DPython3_EXECUTABLE=$CONDA_PREFIX/bin/python
#   cmake --build build
#
# The build type matters: a stage module exists to be measured against its
# Python backend, and an unoptimized one measures as a regression
# (einsums_add_stage_module defaults an EMPTY build type to Release for that
# reason, but say what you mean). The conda prefix supplies Einsums's
# dependency configs, and the explicit interpreter pins the CPython the
# module imports into.
#
# Then put the resulting {m.module_name} module on PYTHONPATH and select it:
#
#   python driver.py --backend {m.stages[0].name}=cpp

cmake_minimum_required(VERSION 3.22)
project({m.module_name} LANGUAGES CXX)

# COMPONENTS stages asks for what a stage module needs and cannot do without: a
# SHARED libEinsums. Shared-graph capture keeps its capture context in
# thread-local state inside the library, so a statically linked module gets its
# own copy and silently captures into a graph nobody executes.
#
# This also finds pybind11, at the exact version einsums._core was built with.
# Repeating that find_package here would be redundant: pybind11 only shares
# types between modules whose internals agree, so the version is Einsums's to
# dictate rather than ours to choose.
find_package(Einsums REQUIRED COMPONENTS stages)

# Wraps pybind11_add_module, the link, and the language standard - the last of
# which is the one worth not hand-rolling. A module compiled at a different
# standard than the library folds a different __cplusplus into the config
# fingerprint and is refused at import, and may fail to dlopen before the
# handshake can say so.
einsums_add_stage_module(
  {m.module_name}
  SOURCES {sources}
  INCLUDE_DIRS ${{CMAKE_CURRENT_SOURCE_DIR}}/include
)
"""

    # -- src/<Stage>.cpp ------------------------------------------------
    def _skeleton_cpp(self, st) -> str:
        m = self.model
        params = ",\n".join(f"    {p.decl}" for p in st.params)
        body = (
            "    // TODO: port.\n"
            if st.return_cpp == "void"
            else f"    // TODO: port.\n    return {st.return_cpp}{{}};\n"
        )
        reference = "\n".join(f"// {line}".rstrip() for line in st.python_source.split("\n"))
        return f"""
#include <{m.namespace}/{st.unit}.hpp>

#include <Einsums/ComputeGraph.hpp>

namespace cg = einsums::compute_graph;

namespace {m.namespace} {{

{st.return_cpp} {st.name}(
{params}) {{
{body}}}

}} // namespace {m.namespace}

// The Python backend this replaces, for reference while porting. Delete it
// once the port is done: two copies of the same algorithm in one file is a
// second thing to keep in step, and the Python one is already in the Python.
//
{reference}
"""

    # -- tests/test_diff_<stage>.py -------------------------------------
    def _diff_test(self, st) -> str:
        m = self.model
        return f'''
"""Differential test for the ``{st.name}`` stage: python against cpp.

Fill in ``make_inputs``. Until you do, this test skips - visibly, naming the
one thing it needs - rather than passing and looking like coverage.

The comparison uses the contract's own ``cmp`` rules, so a field declared
``up_to_sign`` is compared that way here without this file knowing which field
that is. That is the point of putting the rules on the contract.
"""

import pytest

from einsums import stages

import {m.source_module}  # noqa: F401  (registers the python backend)


def make_inputs():
    """Return the keyword arguments to call the stage with.

    TODO: build inputs small enough for CI. The other path is
    ``stages.record(names=["{st.name}"], out_dir=...)`` on a real run,
    which serializes inputs and outputs for replay and needs no synthetic case.
    """
    return None


@pytest.fixture(scope="module")
def stage_module():
    return stages.load_stage_module("{m.module_name}")


def test_{st.name}_backends_agree(stage_module):
    inputs = make_inputs()
    if inputs is None:
        pytest.skip("make_inputs() is not filled in yet")

    from einsums.stages import compare

    st = stages.get_stage("{st.name}")

    st.select("python")
    expected = st.call(**inputs)
    st.select("cpp")
    actual = st.call(**inputs)

    compare.assert_contract_equal(expected, actual)
'''


def generate(model, out_dir, **kwargs) -> list[Written]:
    """Render *model* into *out_dir*. See :class:`Emitter` for the options."""
    return Emitter(model, out_dir, **kwargs).run()


@_dataclasses.dataclass(frozen=True)
class Formatters:
    """The formatting tools promote will run its output through."""

    clang_format: str | None
    cmake_format: str | None

    @property
    def missing(self) -> tuple:
        return tuple(
            name
            for name, found in (("clang-format", self.clang_format), ("cmake-format", self.cmake_format))
            if found is None
        )


def _which(explicit: str | None, default: str) -> str | None:
    if explicit:
        found = _shutil.which(explicit) or (explicit if _pathlib.Path(explicit).is_file() else None)
        if found is None:
            raise PromoteError(f"{default} not found at {explicit!r}")
        return found
    return _shutil.which(default)


def find_formatters(clang_format=None, cmake_format=None, enabled: bool = True) -> Formatters:
    """Locate the formatters, preferring explicitly named binaries."""
    if not enabled:
        return Formatters(None, None)
    return Formatters(_which(clang_format, "clang-format"), _which(cmake_format, "cmake-format"))
