#----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#----------------------------------------------------------------------------------------------

# einsums_finalize_pybind() assembles the autogenerated bindings from
# every module that opted into ``einsums_add_module(... PYBIND ...)``
# into a single ``PyEinsums`` Python extension that exposes them all
# under one ``import einsums`` call.
#
# Must run AFTER ``add_subdirectory(libs)`` because each annotated
# module appends to GLOBAL properties:
#
#     EINSUMS_PYBIND_MODULES                 : list of module names
#     EINSUMS_PYBIND_LINK_TARGETS            : list of einsums library targets
#     EINSUMS_PYBIND_HEADERS_<MODULE>        : absolute header paths
#     EINSUMS_PYBIND_RELHEADERS_<MODULE>     : relative-to-HEADER_ROOT names
#     EINSUMS_PYBIND_INCFLAGS_<MODULE>       : module-specific -I flags
#     EINSUMS_PYBIND_LIBNAME_<MODULE>        : owning library name (Einsums)
#
# Per-module ``add_custom_command(OUTPUT)`` calls are emitted here at
# root scope so the consuming ``target_sources(PyEinsums PRIVATE ...)``
# stays in the same directory; CMake silently drops cross-scope
# custom-command outputs from a target's source list otherwise.


function(einsums_finalize_pybind)
    if(NOT EINSUMS_BUILD_PYTHON)
        return()
    endif()

    get_property(_modules GLOBAL PROPERTY EINSUMS_PYBIND_MODULES)
    get_property(_targets GLOBAL PROPERTY EINSUMS_PYBIND_LINK_TARGETS)

    if(NOT _modules)
        message(STATUS "apiary: no modules opted in via PYBIND — skipping aggregator.")
        return()
    endif()


    # Configure-time-generated Defines.hpp files. Adding them to every
    # codegen edge's DEPENDS makes the codegen re-fire when configure
    # toggles a flag (EINSUMS_WITH_GPU=ON, ...); the regenerated
    # Defines.hpp changes mtime, so any annotated header that uses
    # ``#if defined(EINSUMS_HAVE_GPU)`` produces fresh output. Each
    # module writes its own ``${BUILD}/libs/<Lib>/<Mod>/include/<Lib>/<Mod>/Defines.hpp``
    # via einsums_write_config_defines_file, so a recursive glob picks
    # them all up.
    file(GLOB_RECURSE _all_defines_headers
        "${PROJECT_BINARY_DIR}/libs/*/Defines.hpp"
    )

    # spdlog is built from source (FetchContent) because conda ships no
    # fmt-12-compatible spdlog, so its headers live in the build tree rather
    # than the env include apiary already sees. Modules whose public headers
    # include <spdlog/...> (e.g. Logging) would otherwise fail codegen with
    # "spdlog/sinks/sink.h not found". Hand apiary that include dir and
    # SPDLOG_FMT_EXTERNAL so it parses spdlog against the external fmt rather
    # than spdlog's bundled copy.
    set(_apiary_spdlog_flags "")
    if(spdlog_SOURCE_DIR)
        list(APPEND _apiary_spdlog_flags "-DSPDLOG_FMT_EXTERNAL" "-I${spdlog_SOURCE_DIR}/include")
    endif()

    # Emit one add_custom_command per opted-in module producing its
    # generated TU.
    set(_generated_tus "")
    set(_docs_jsons "")
    foreach(_mod IN LISTS _modules)
        get_property(_headers      GLOBAL PROPERTY EINSUMS_PYBIND_HEADERS_${_mod})
        get_property(_relheaders   GLOBAL PROPERTY EINSUMS_PYBIND_RELHEADERS_${_mod})
        get_property(_deps         GLOBAL PROPERTY EINSUMS_PYBIND_DEPS_${_mod})
        get_property(_header_root  GLOBAL PROPERTY EINSUMS_PYBIND_HEADER_ROOT_${_mod})
        get_property(_bin_inc      GLOBAL PROPERTY EINSUMS_PYBIND_BIN_INC_${_mod})
        get_property(_libname      GLOBAL PROPERTY EINSUMS_PYBIND_LIBNAME_${_mod})

        # apiary_add_bindings populates these via OUT_* (PARENT_SCOPE);
        # pre-declare so the static cmake-audit check sees them defined.
        set(_out "")
        set(_stub_out "")
        set(_docs_json "")
        apiary_add_bindings(
            BINDING DOCS_JSON
            HEADERS ${_headers}
            SOURCE_INCLUDES ${_relheaders}
            REGISTER_FUNCTION apiary_register_${_mod}
            MODULE einsums
            DEPENDS_TARGETS ${_deps}
            OUTPUT_DIR "${CMAKE_BINARY_DIR}/generated/pybind"
            OUTPUT_NAME "${_libname}_${_mod}"
            CXX_STANDARD ${EINSUMS_WITH_CXX_STANDARD}
            # Module-local include roots not carried by the dependency targets'
            # usage requirements: the module's own source + build include dirs,
            # the build root (Config.hpp), the annotations shim, and apiary's
            # own headers.
            EXTRA_FLAGS
                "-I${_header_root}"
                "-I${_bin_inc}"
                "-I${CMAKE_BINARY_DIR}"
                "-I${CMAKE_SOURCE_DIR}/libs/Einsums/Python/include"
                "-I${CMAKE_SOURCE_DIR}/external/apiary/include"
                ${_apiary_spdlog_flags}
            EXTRA_DEPENDS ${_all_defines_headers}
            OUT_BINDING _out OUT_STUB _stub_out OUT_DOCS_JSON _docs_json
        )
        list(APPEND _generated_tus   "${_out}")
        list(APPEND _generated_stubs "${_stub_out}")
        list(APPEND _docs_jsons      "${_docs_json}")
    endforeach()

    # --- Assemble the single ``_core`` extension via apiary ----------------
    set(_pkg_dir  "${CMAKE_BINARY_DIR}/lib/einsums")
    set(_pkg_src  "${CMAKE_SOURCE_DIR}/libs/Einsums/Python/python/einsums")
    set(_gen_dir  "${CMAKE_BINARY_DIR}/generated/pybind")
    set(_main_cpp "${CMAKE_SOURCE_DIR}/libs/Einsums/Python/src/PyEinsumsMain.cpp")

    # Land the checked-in Python shell files into the package dir. configure_file
    # COPYONLY tracks source mtime so edits trigger a re-configure (the runtime
    # copy never goes stale).
    file(MAKE_DIRECTORY "${_pkg_dir}")
    configure_file("${_pkg_src}/__init__.py" "${_pkg_dir}/__init__.py" COPYONLY)
    configure_file("${_pkg_src}/rc.py"       "${_pkg_dir}/rc.py"       COPYONLY)
    configure_file("${_pkg_src}/graph.py"    "${_pkg_dir}/graph.py"    COPYONLY)
    configure_file("${_pkg_src}/profile.py"  "${_pkg_dir}/profile.py"  COPYONLY)
    configure_file("${_pkg_src}/sealed.py"   "${_pkg_dir}/sealed.py"   COPYONLY)
    file(MAKE_DIRECTORY "${_pkg_dir}/testing")
    configure_file("${_pkg_src}/testing/__init__.py" "${_pkg_dir}/testing/__init__.py" COPYONLY)
    file(MAKE_DIRECTORY "${_pkg_dir}/interop")
    configure_file("${_pkg_src}/interop/__init__.py" "${_pkg_dir}/interop/__init__.py" COPYONLY)
    configure_file("${_pkg_src}/interop/psi4.py"     "${_pkg_dir}/interop/psi4.py"     COPYONLY)
    # Globbed rather than listed. The stages package grows a file per milestone,
    # and a name missing from an explicit list does not fail the build - it ships
    # a package whose import fails at runtime, in the copy under lib/ only, which
    # is the hardest place to notice it.
    file(MAKE_DIRECTORY "${_pkg_dir}/stages")
    file(GLOB _stages_py CONFIGURE_DEPENDS "${_pkg_src}/stages/*.py")
    foreach(_f IN LISTS _stages_py)
        get_filename_component(_name "${_f}" NAME)
        configure_file("${_f}" "${_pkg_dir}/stages/${_name}" COPYONLY)
    endforeach()
    file(GLOB _py_helpers     CONFIGURE_DEPENDS "${_pkg_src}/*.py")
    file(GLOB _py_helper_pkgs CONFIGURE_DEPENDS "${_pkg_src}/*/*.py")

    apiary_aggregate_extension(
        NAME PyEinsums
        MAIN "${_main_cpp}"
        BINDINGS ${_generated_tus}
        MODULES ${_modules}
        REGISTER_PREFIX apiary_register_
        MODULES_HEADER      "${_gen_dir}/include/Einsums/Python/Detail/PyEinsumsModules.hpp"
        MODULES_INCLUDE_DIR "${_gen_dir}/include"
        STUBS ${_generated_stubs}
        STUBS_TARGET PyEinsumsStubs
        FRAG_DIR "${_gen_dir}"
        PKG_DIR "${_pkg_dir}"
        PY_HELPERS_DIR "${_pkg_src}"
        PY_HELPER_DEPENDS ${_py_helpers} ${_py_helper_pkgs}
        # Einsums-owned overlay for the runtime-patched NumPy-style ergonomics
        # that the C++ codegen can't see: conj, .real, .imag, .H, the constructors,
        # and so on. Apiary supplies the merge mechanism; the content and class
        # regex live here.
        STUB_OVERLAY "${CMAKE_SOURCE_DIR}/libs/Einsums/Python/stub_overlay.pyi"
        STUB_OVERLAY_CLASS_REGEX "^class (RuntimeTensor(View)?[FDCZ]): *$"
        DOCS_JSON ${_docs_jsons}
        DOCS_TARGET PyEinsumsDocs
        DOCS_OUTDIR "${_gen_dir}/docs"
    )

    einsums_register_python_extension(PyEinsums)

    # _core extension lands as lib/einsums/_core.* alongside the shell files.
    set_target_properties(PyEinsums PROPERTIES
        OUTPUT_NAME _core
        LIBRARY_OUTPUT_DIRECTORY "${_pkg_dir}"
    )
    # Einsums_SetOutputPaths sets the PER-CONFIG output variables under MSVC
    # (build/<Config>/lib), and a per-config property beats the plain one, so
    # the line above would be ignored there and _core.pyd would miss the
    # package directory PYTHONPATH points at. Pin every config explicitly.
    if(MSVC)
        set(_pyd_configs ${CMAKE_CONFIGURATION_TYPES})
        if(NOT _pyd_configs)
            set(_pyd_configs "${CMAKE_BUILD_TYPE}")
        endif()
        foreach(_cfg IN LISTS _pyd_configs)
            string(TOUPPER "${_cfg}" _cfg_upper)
            set_target_properties(PyEinsums PROPERTIES
                LIBRARY_OUTPUT_DIRECTORY_${_cfg_upper} "${_pkg_dir}"
                RUNTIME_OUTPUT_DIRECTORY_${_cfg_upper} "${_pkg_dir}"
            )
        endforeach()

        # Windows has no RPATH: an extension resolves its dependent DLLs from
        # its own directory, the directories registered with
        # os.add_dll_directory, and the system directories - never from PATH
        # (CPython 3.8+). Copying Einsums.dll in beside _core.pyd is what makes
        # `import einsums` work from a plain build tree, and mirrors the
        # vendored layout a wheel would ship. The package's __init__ registers
        # the conda environment for the third-party DLLs underneath it.
        # The $<IF:...> picks ``cmake -E true`` when the DLL list is empty (a
        # static Einsums), because copy_if_different with no sources is an
        # error rather than a no-op.
        add_custom_command(TARGET PyEinsums POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E
                    $<IF:$<BOOL:$<TARGET_RUNTIME_DLLS:PyEinsums>>,copy_if_different,true>
                    $<TARGET_RUNTIME_DLLS:PyEinsums> "$<TARGET_FILE_DIR:PyEinsums>"
            COMMAND_EXPAND_LISTS
            COMMENT "Copying runtime DLLs next to the einsums extension"
        )
    endif()
    # Link only the umbrella ``Einsums`` shared library. Linking the per-module
    # targets (${_targets}) as well baked each module's object files into _core.so
    # on top of libEinsums.dylib, duplicating code/RTTI. Everything _core needs is
    # in libEinsums.dylib, so we rely on it alone; any symbol the bindings
    # reference must therefore be exported by libEinsums (EINSUMS_EXPORT). With
    # EINSUMS_WITH_HIDDEN_VISIBILITY off (the Apple/Clang default) it has default
    # visibility and exports everything; if hidden visibility is turned on, the
    # bindings' referenced symbols must carry EINSUMS_EXPORT.
    target_link_libraries(PyEinsums PRIVATE Einsums)
    # ``einsums_private_flags`` carries project-wide compile-time switches the
    # per-module targets pick up via einsums_add_module. pybind11_add_module
    # creates a fresh target that does not link against it transitively, so
    # without this PyEinsums compiles with raw conda flags and trips warnings
    # our private-flags target was set up to silence, most visibly the GCC
    # ``-Winterference-size`` from Profile/RingBuffer.hpp's use of
    # ``std::hardware_destructive_interference_size``. Adding it here mirrors
    # what einsums_add_executable does for ordinary in-tree targets.
    if(TARGET einsums_private_flags)
        target_link_libraries(PyEinsums PRIVATE einsums_private_flags)
    endif()

    list(LENGTH _modules _count)
    message(STATUS "apiary: PyEinsums aggregates ${_count} module(s): ${_modules}")

    # Wire pseudo-targets registered by einsums_add_python_unit_test() to
    # depend on PyEinsums. The function can't do this itself because it runs
    # before the PyEinsums target exists.
    #
    # Through einsums_add_pseudo_dependencies, not add_dependencies: the
    # registered names are the full dotted ones, and pseudo targets do not
    # necessarily exist under those names. Windows forces
    # EINSUMS_WITH_PSEUDO_DEPENDENCIES OFF, so none of them exist at all, and
    # the shortener collapses a dotted name to its last element everywhere
    # else on WIN32. The helper applies both rules, so it no-ops where the
    # raw call would fail on a non-existent target.
    get_property(_pyt_targets GLOBAL PROPERTY EINSUMS_PYTHON_UNIT_TEST_TARGETS)
    foreach(_pyt_target IN LISTS _pyt_targets)
        einsums_add_pseudo_dependencies("${_pyt_target}" PyEinsums)
    endforeach()
endfunction()
