#----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#----------------------------------------------------------------------------------------------
#
#.rst:
# Einsums_SymbolIsolation
# -----------------------
#
# Keep two copies of libEinsums in one process from answering for each other.
#
# A host application may link its own private Einsums while a developer loads a
# newer one alongside it. That is supported; the rule that makes it safe is that
# typed objects never cross between the two. What must not happen is the two
# copies silently sharing symbols, because then they share the thread-local
# capture context, the plan caches, and every function-local static behind an
# exported function.
#
# Only ELF has the flat symbol namespace that allows it. Mach-O records the
# source dylib per binding at link time and PE binds per-DLL by name, so both
# are already safe and neither linker accepts these flags.
#
# The mechanism is reproduced and verified end to end in
# ``libs/Einsums/Config/tests/unit/two_worlds``: without the version script two
# consumers loaded RTLD_GLOBAL both reach the first-loaded copy; with it each
# reaches its own.

include_guard(GLOBAL)

#[[.rst:
.. cmake:command:: einsums_apply_symbol_isolation

   Version and hide the exported symbols of a shared library so a second copy in
   the same process cannot interpose on it.

   ``einsums_apply_symbol_isolation(<target>)``

   Does nothing on non-ELF platforms, or where the linker rejects the flags.
]]
function(einsums_apply_symbol_isolation target)
  get_target_property(_type ${target} TYPE)
  if(NOT _type STREQUAL "SHARED_LIBRARY")
    return()
  endif()

  # --- symbols absorbed from static archives ---------------------------------
  #
  # Anything folded in from a static library (spdlog today, HPTT until it moved into the einsums
  # namespace) keeps whatever visibility it was built with and lands in our dynamic symbol table
  # under ITS name, not ours. Two worlds absorbing different vintages of the same third-party code
  # then interpose on each other, and no namespace scheme in our own sources can reach that.
  # `--exclude-libs,ALL` drops every such symbol from the dynamic table.
  if(NOT WIN32 AND NOT APPLE)
    include(CheckLinkerFlag)
    check_linker_flag(CXX "LINKER:--exclude-libs,ALL" EINSUMS_LINKER_HAS_EXCLUDE_LIBS)
    if(EINSUMS_LINKER_HAS_EXCLUDE_LIBS)
      target_link_options(${target} PRIVATE "LINKER:--exclude-libs,ALL")
    endif()
  endif()

  # --- versioned symbols -----------------------------------------------------
  #
  # Tag every exported symbol with this ABI generation. A consumer then records a versioned
  # REFERENCE, so when some other package in the process has already put an incompatible copy into
  # the global lookup scope, the dynamic linker rejects the version mismatch and keeps searching
  # rather than binding to it.
  #
  # Owned limitation: this settles matters against a peer that is itself versioned. Against a LEGACY
  # unversioned libEinsums, glibc accepts an unversioned definition for a versioned reference unless
  # the object is the one named in the verneed entry, which it will not be. Nothing here can fix a
  # copy that shipped before this existed; the runtime handshake in <Einsums/Config/ABI.hpp> is what
  # turns that case into a refusal.
  if(NOT WIN32 AND NOT APPLE)
    set(_map "${CMAKE_BINARY_DIR}/einsums-abi${EINSUMS_ABI_VERSION}.map")
    # `global: *` versions everything that is exported without changing WHICH symbols are exported;
    # that stays governed by -fvisibility=hidden and EINSUMS_EXPORT. A `local: *` here would instead
    # hide the entire API.
    file(WRITE "${_map}" "# Generated by Einsums_SymbolIsolation.cmake. Do not edit.\n"
                         "EINSUMS_${EINSUMS_ABI_VERSION} {\n" "  global: *;\n" "};\n"
    )
    include(CheckLinkerFlag)
    check_linker_flag(CXX "LINKER:--version-script=${_map}" EINSUMS_LINKER_HAS_VERSION_SCRIPT)
    if(EINSUMS_LINKER_HAS_VERSION_SCRIPT)
      target_link_options(${target} PRIVATE "LINKER:--version-script=${_map}")
      # A version script is a link INPUT, not merely a flag. Without this the library does not
      # relink when it changes, and a botched script would keep passing out of the build cache.
      set_property(
        TARGET ${target}
        APPEND
        PROPERTY LINK_DEPENDS "${_map}"
      )
    endif()
  endif()
endfunction()
