#----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#----------------------------------------------------------------------------------------------

# einsums_finalize_pybind() — assemble the autogenerated bindings from
# every module that opted into ``einsums_add_module(... PYBIND ...)``
# into a single ``PyEinsums`` Python extension that exposes them all
# under one ``import einsums`` call.
#
# Must run AFTER ``add_subdirectory(libs)`` because each annotated
# module appends to GLOBAL properties:
#
#     EINSUMS_PYBIND_MODULES                 — list of module names
#     EINSUMS_PYBIND_LINK_TARGETS            — list of einsums library targets
#     EINSUMS_PYBIND_HEADERS_<MODULE>        — absolute header paths
#     EINSUMS_PYBIND_RELHEADERS_<MODULE>     — relative-to-HEADER_ROOT names
#     EINSUMS_PYBIND_INCFLAGS_<MODULE>       — module-specific -I flags
#     EINSUMS_PYBIND_LIBNAME_<MODULE>        — owning library name (Einsums)
#
# Per-module ``add_custom_command(OUTPUT)`` calls are emitted here at
# root scope so the consuming ``target_sources(PyEinsums PRIVATE ...)``
# stays in the same directory — CMake silently drops cross-scope
# custom-command outputs from a target's source list otherwise.

# Recursively collect BUILD_INTERFACE include dirs AND
# INTERFACE_COMPILE_DEFINITIONS reachable from `target` via
# INTERFACE_LINK_LIBRARIES. CMake has no built-in for this; walking by
# hand is reliable since INTERFACE_LINK_LIBRARIES is set explicitly by
# einsums_add_module via target_link_libraries.
#
# Defines flow through to the codegen as ``-D<def>`` flags so headers
# can use ``#if defined(EINSUMS_HAVE_GPU)`` etc. to conditionally include
# different EINSUMS_PYBIND_INSTANTIATE lines. The set is dominated by
# definitions added via einsums_add_config_define, but anything set on a
# target via target_compile_definitions also rides along.
function(_einsums_pybind_collect_transitive_includes target inc_out_var def_out_var visited_var)
    if(NOT TARGET ${target})
        return()
    endif()
    # CMake function scope quirk: when we ``set(${out_var} ... PARENT_SCOPE)``
    # the parent's variable updates but our LOCAL copy of that variable
    # (inherited at function-entry time) does NOT. Recursive callees
    # inherit OUR local copy, not the parent's, so we must keep the two
    # in sync — local set() for visibility to recursive children, then
    # PARENT_SCOPE set() at exit for propagation back up.
    set(_local_inc     "${${inc_out_var}}")
    set(_local_def     "${${def_out_var}}")
    set(_local_visited "${${visited_var}}")

    if("${target}" IN_LIST _local_visited)
        return()
    endif()
    list(APPEND _local_visited "${target}")

    get_target_property(_inc ${target} INTERFACE_INCLUDE_DIRECTORIES)
    if(_inc)
        foreach(_dir IN LISTS _inc)
            set(_path "")
            string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.+)>$" "\\1" _path "${_dir}")
            if(NOT _path STREQUAL "${_dir}")
                list(APPEND _local_inc "${_path}")
            elseif(_dir MATCHES "^\\$<")
                # skip other genex
            else()
                list(APPEND _local_inc "${_dir}")
            endif()
        endforeach()
    endif()

    get_target_property(_def ${target} INTERFACE_COMPILE_DEFINITIONS)
    if(_def)
        foreach(_d IN LISTS _def)
            set(_clean "")
            string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.+)>$" "\\1" _clean "${_d}")
            if(NOT _clean STREQUAL "${_d}")
                list(APPEND _local_def "${_clean}")
            elseif(_d MATCHES "^\\$<")
                # skip other genex (e.g. config-conditional defines we
                # can't evaluate at configure time)
            else()
                list(APPEND _local_def "${_d}")
            endif()
        endforeach()
    endif()

    # Make the local accumulators visible to recursive children via the
    # function's own scope (their inherited copy will see these values).
    set(${inc_out_var}     "${_local_inc}")
    set(${def_out_var}     "${_local_def}")
    set(${visited_var}     "${_local_visited}")

    get_target_property(_link ${target} INTERFACE_LINK_LIBRARIES)
    if(_link)
        foreach(_dep IN LISTS _link)
            if(TARGET ${_dep})
                _einsums_pybind_collect_transitive_includes("${_dep}" ${inc_out_var} ${def_out_var} ${visited_var})
                # Recursive callee writes via PARENT_SCOPE which updates
                # THIS function's scope — re-read into our locals so
                # the next iteration sees its progress.
                set(_local_inc     "${${inc_out_var}}")
                set(_local_def     "${${def_out_var}}")
                set(_local_visited "${${visited_var}}")
            endif()
        endforeach()
    endif()

    set(${inc_out_var} "${_local_inc}"     PARENT_SCOPE)
    set(${def_out_var} "${_local_def}"     PARENT_SCOPE)
    set(${visited_var} "${_local_visited}" PARENT_SCOPE)
endfunction()

function(einsums_finalize_pybind)
    if(NOT EINSUMS_BUILD_PYTHON)
        return()
    endif()

    get_property(_modules GLOBAL PROPERTY EINSUMS_PYBIND_MODULES)
    get_property(_targets GLOBAL PROPERTY EINSUMS_PYBIND_LINK_TARGETS)

    if(NOT _modules)
        message(STATUS "apiary: no modules opted in via PYBIND — skipping aggregator.")
        return()
    endif()

    # System / SDK paths required for libtooling to find ``<string>``,
    # ``<stdarg.h>``, etc. Same set for every per-module invocation.
    set(_pyb_system_flags "")
    if(EINSUMS_PYBIND_CLANG_RESOURCE_DIR)
        list(APPEND _pyb_system_flags "-resource-dir" "${EINSUMS_PYBIND_CLANG_RESOURCE_DIR}")
    endif()
    if(EINSUMS_PYBIND_SYSROOT)
        list(APPEND _pyb_system_flags "-isysroot" "${EINSUMS_PYBIND_SYSROOT}")
    endif()
    if(EINSUMS_PYBIND_EXTRA_ISYSTEM)
        list(APPEND _pyb_system_flags "-isystem" "${EINSUMS_PYBIND_EXTRA_ISYSTEM}")
    endif()
    # The actual project compiler's C++ standard-library / system header
    # search dirs (probed at configure time). Without these the libtooling
    # parse can't find ``<complex>`` and friends when the build compiler is
    # gcc (libstdc++) rather than the clang that backs apiary.
    foreach(_cxx_dir IN LISTS EINSUMS_PYBIND_CXX_INCLUDE_DIRS)
        list(APPEND _pyb_system_flags "-isystem" "${_cxx_dir}")
    endforeach()

    # Configure-time-generated Defines.hpp files. Adding them to every
    # codegen edge's DEPENDS makes the codegen re-fire when configure
    # toggles a flag (EINSUMS_WITH_GPU=ON, ...) — the regenerated
    # Defines.hpp changes mtime, so any annotated header that uses
    # ``#if defined(EINSUMS_HAVE_GPU)`` produces fresh output. Each
    # module writes its own ``${BUILD}/libs/<Lib>/<Mod>/include/<Lib>/<Mod>/Defines.hpp``
    # via einsums_write_config_defines_file, so a recursive glob picks
    # them all up.
    file(GLOB_RECURSE _all_defines_headers
        "${PROJECT_BINARY_DIR}/libs/*/Defines.hpp"
    )

    # Emit one add_custom_command per opted-in module producing its
    # generated TU.
    set(_generated_tus "")
    set(_docs_jsons "")
    foreach(_mod IN LISTS _modules)
        get_property(_headers      GLOBAL PROPERTY EINSUMS_PYBIND_HEADERS_${_mod})
        get_property(_relheaders   GLOBAL PROPERTY EINSUMS_PYBIND_RELHEADERS_${_mod})
        get_property(_deps         GLOBAL PROPERTY EINSUMS_PYBIND_DEPS_${_mod})
        get_property(_header_root  GLOBAL PROPERTY EINSUMS_PYBIND_HEADER_ROOT_${_mod})
        get_property(_bin_inc      GLOBAL PROPERTY EINSUMS_PYBIND_BIN_INC_${_mod})
        get_property(_libname      GLOBAL PROPERTY EINSUMS_PYBIND_LIBNAME_${_mod})

        set(_inc_flags
            "-I${_header_root}"
            "-I${_bin_inc}"
            "-I${CMAKE_BINARY_DIR}"
            "-I${CMAKE_SOURCE_DIR}/libs/Einsums/Python/include"
            "-I${CMAKE_SOURCE_DIR}/external/apiary/include"
        )
        # Walk MODULE_DEPENDENCIES TRANSITIVELY at finalize time. Every
        # Einsums module target exists by now, including ones declared
        # later in libs/Einsums/CMakeLists.txt than the caller. Recursing
        # via INTERFACE_LINK_LIBRARIES catches indirect dependencies
        # (e.g. Tensor's Config -> Preprocessor) that aren't in the
        # caller's MODULE_DEPENDENCIES list. Walks both include dirs and
        # compile definitions in one pass.
        set(_collected_dirs "")
        set(_collected_defs "")
        set(_visited "")
        foreach(_dep IN LISTS _deps)
            _einsums_pybind_collect_transitive_includes("${_dep}" _collected_dirs _collected_defs _visited)
        endforeach()
        list(REMOVE_DUPLICATES _collected_dirs)
        list(REMOVE_DUPLICATES _collected_defs)
        foreach(_dir IN LISTS _collected_dirs)
            list(APPEND _inc_flags "-I${_dir}")
        endforeach()
        # Forward compile definitions as ``-D`` flags so headers can use
        # ``#if defined(EINSUMS_HAVE_GPU)`` to gate INSTANTIATE choices
        # on configure-time options.
        set(_def_flags "")
        foreach(_d IN LISTS _collected_defs)
            list(APPEND _def_flags "-D${_d}")
        endforeach()

        set(_out      "${CMAKE_BINARY_DIR}/generated/pybind/${_libname}_${_mod}_pybind.cpp")
        set(_stub_out "${CMAKE_BINARY_DIR}/generated/pybind/${_libname}_${_mod}.pyi")

        set(_source_includes "")
        foreach(_h IN LISTS _relheaders)
            list(APPEND _source_includes --source-include "${_h}")
        endforeach()

        add_custom_command(
            OUTPUT ${_out} ${_stub_out}
            COMMAND ${CMAKE_COMMAND} -E make_directory
                    "${CMAKE_BINARY_DIR}/generated/pybind"
            COMMAND $<TARGET_FILE:apiary>
                    --register-function apiary_register_${_mod}
                    --output ${_out}
                    --stub-output ${_stub_out}
                    ${_source_includes}
                    ${_headers}
                    --
                    -std=c++${EINSUMS_WITH_CXX_STANDARD}
                    ${_pyb_system_flags}
                    ${_def_flags}
                    ${_inc_flags}
            DEPENDS ${_headers} apiary ${_all_defines_headers}
            VERBATIM
            COMMENT "apiary: generating ${_libname}_${_mod}_pybind.cpp + .pyi"
        )
        list(APPEND _generated_tus   "${_out}")
        list(APPEND _generated_stubs "${_stub_out}")

        # Documentation JSON: the same parse, emitted as a tool-agnostic
        # description of the Python-facing surface (see DocsJson.hpp). The
        # render step (PyEinsumsDocs below) turns these into reST. Same
        # flags as the binding command minus the binding-only options.
        set(_docs_json "${CMAKE_BINARY_DIR}/generated/pybind/${_libname}_${_mod}.docs.json")
        add_custom_command(
            OUTPUT ${_docs_json}
            COMMAND ${CMAKE_COMMAND} -E make_directory
                    "${CMAKE_BINARY_DIR}/generated/pybind"
            COMMAND $<TARGET_FILE:apiary>
                    --emit-docs-json
                    --module einsums
                    --output ${_docs_json}
                    ${_source_includes}
                    ${_headers}
                    --
                    -std=c++${EINSUMS_WITH_CXX_STANDARD}
                    ${_pyb_system_flags}
                    ${_def_flags}
                    ${_inc_flags}
            DEPENDS ${_headers} apiary ${_all_defines_headers}
            VERBATIM
            COMMENT "apiary: emitting docs JSON for ${_libname}_${_mod}"
        )
        list(APPEND _docs_jsons "${_docs_json}")
    endforeach()

    # Generate the tiny per-module list header consumed by the static
    # ``PyEinsumsMain.cpp`` aggregator. This is the only piece that varies
    # with the enabled-module set; everything else (init, atexit,
    # PYBIND11_MODULE body) lives in checked-in C++ source.
    set(_prototypes "")
    set(_calls "")
    foreach(_mod IN LISTS _modules)
        set(_prototypes "${_prototypes}void apiary_register_${_mod}(::pybind11::module_ &m);\n")
        set(_calls      "${_calls}    apiary_register_${_mod}(m);\n")
    endforeach()

    set(_modules_hdr_dir "${CMAKE_BINARY_DIR}/generated/pybind/include/Einsums/Python/Detail")
    set(_modules_hdr     "${_modules_hdr_dir}/PyEinsumsModules.hpp")
    file(MAKE_DIRECTORY "${_modules_hdr_dir}")
    file(WRITE "${_modules_hdr}"
"// This file is generated by einsums_finalize_pybind. Do not edit.\n"
"//\n"
"// Per-module register function declarations and the inline aggregator\n"
"// called from PyEinsumsMain.cpp's PYBIND11_MODULE body. The list of\n"
"// modules tracks which Einsums libraries opted in via\n"
"// einsums_add_module(... PYBIND ON).\n"
"\n"
"#pragma once\n"
"\n"
"#include <pybind11/pybind11.h>\n"
"\n"
"${_prototypes}"
"\n"
"inline void apiary_register_all(::pybind11::module_ &m) {\n"
"${_calls}"
"}\n"
    )

    set(_main_cpp "${CMAKE_SOURCE_DIR}/libs/Einsums/Python/src/PyEinsumsMain.cpp")
    pybind11_add_module(PyEinsums "${_main_cpp}" ${_generated_tus})
    set_target_properties(PyEinsums PROPERTIES OUTPUT_NAME _core)
    # The static main needs to find the autogenerated modules header.
    target_include_directories(PyEinsums PRIVATE "${CMAKE_BINARY_DIR}/generated/pybind/include")

    # Land the compiled extension and the Python shell files together as
    # a proper package: ``${CMAKE_BINARY_DIR}/lib/einsums/{_core.so,
    # __init__.py, rc.py}``. The .py files are checked-in static sources
    # under libs/Einsums/Python/python/einsums/ and copied verbatim.
    set(_pkg_dir "${CMAKE_BINARY_DIR}/lib/einsums")
    set_target_properties(PyEinsums PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${_pkg_dir}")
    set(_pkg_src "${CMAKE_SOURCE_DIR}/libs/Einsums/Python/python/einsums")
    file(MAKE_DIRECTORY "${_pkg_dir}")
    # configure_file(... COPYONLY) tracks the source mtime as a configure-time
    # dependency: editing any of these files triggers an automatic re-configure
    # on the next build, so the package's runtime copy never goes stale. (The
    # earlier ``file(COPY)`` ran once and required a manual ``cmake -B build``
    # to pick up edits.)
    configure_file("${_pkg_src}/__init__.py" "${_pkg_dir}/__init__.py" COPYONLY)
    configure_file("${_pkg_src}/rc.py"       "${_pkg_dir}/rc.py"       COPYONLY)
    configure_file("${_pkg_src}/graph.py"    "${_pkg_dir}/graph.py"    COPYONLY)
    configure_file("${_pkg_src}/profile.py"  "${_pkg_dir}/profile.py"  COPYONLY)
    # einsums.testing — pure-Python sub-package of test helpers.
    file(MAKE_DIRECTORY "${_pkg_dir}/testing")
    configure_file("${_pkg_src}/testing/__init__.py"
                   "${_pkg_dir}/testing/__init__.py" COPYONLY)

    # Aggregate per-module .pyi fragments into per-submodule stub files
    # (einsums/_core.pyi, einsums/<sub>.pyi) plus the PEP-561 ``py.typed``
    # marker. The stamp file is what the custom target depends on; touch
    # it whenever any fragment changes.
    set(_stubs_stamp "${CMAKE_BINARY_DIR}/generated/pybind/.stubs.stamp")
    set(_aggregator  "${CMAKE_SOURCE_DIR}/external/apiary/scripts/aggregate_stubs.py")
    # Collect the hand-written .py helpers so editing them re-runs the
    # aggregator (which merges their public surface into the matching
    # <sub>.pyi for pyright). Both top-level files (graph.py, rc.py) and
    # pure-Python helper sub-packages (testing/__init__.py) are tracked
    # so __init__.pyi's submodule re-exports stay in sync.
    file(GLOB _py_helpers      CONFIGURE_DEPENDS "${_pkg_src}/*.py")
    file(GLOB _py_helper_pkgs  CONFIGURE_DEPENDS "${_pkg_src}/*/__init__.py")
    add_custom_command(
        OUTPUT ${_stubs_stamp}
        COMMAND ${Python_EXECUTABLE} ${_aggregator}
                --frag-dir       "${CMAKE_BINARY_DIR}/generated/pybind"
                --pkg-dir        "${_pkg_dir}"
                --py-helpers-dir "${_pkg_src}"
        COMMAND ${CMAKE_COMMAND} -E touch ${_stubs_stamp}
        DEPENDS ${_aggregator} ${_generated_stubs} ${_py_helpers} ${_py_helper_pkgs}
        COMMENT "apiary: aggregating .pyi stubs into ${_pkg_dir}"
        VERBATIM
    )
    add_custom_target(PyEinsumsStubs ALL DEPENDS ${_stubs_stamp})
    add_dependencies(PyEinsumsStubs PyEinsums)

    # Render the per-module docs JSON into a Sphinx Python API reference,
    # grouped by submodule. Deliberately NOT part of ALL — it is built on
    # demand (``cmake --build . --target PyEinsumsDocs``) and is wired as a
    # dependency of the documentation build when EINSUMS_WITH_DOCUMENTATION
    # is on. Pages land in ${_docs_out_dir}; the docs tree pulls them in.
    set(_docs_out_dir  "${CMAKE_BINARY_DIR}/generated/pybind/docs")
    set(_docs_stamp    "${CMAKE_BINARY_DIR}/generated/pybind/.docs.stamp")
    set(_docs_renderer "${CMAKE_SOURCE_DIR}/external/apiary/scripts/render_docs_rst.py")
    add_custom_command(
        OUTPUT ${_docs_stamp}
        COMMAND ${CMAKE_COMMAND} -E make_directory "${_docs_out_dir}"
        COMMAND ${Python_EXECUTABLE} ${_docs_renderer}
                --outdir "${_docs_out_dir}" ${_docs_jsons}
        COMMAND ${CMAKE_COMMAND} -E touch ${_docs_stamp}
        DEPENDS ${_docs_renderer} ${_docs_jsons}
        COMMENT "apiary: rendering Python API reference (.rst) into ${_docs_out_dir}"
        VERBATIM
    )
    add_custom_target(PyEinsumsDocs DEPENDS ${_docs_stamp})
    # Link ONLY the umbrella ``Einsums`` shared library. Linking the per-module
    # targets (${_targets}) as well baked each module's object files into _core.so
    # on top of libEinsums.dylib, duplicating code/RTTI. Everything _core needs is
    # in libEinsums.dylib, so we rely on it alone — any symbol the bindings
    # reference must therefore be exported by libEinsums (EINSUMS_EXPORT). With
    # EINSUMS_WITH_HIDDEN_VISIBILITY off (the Apple/Clang default) it has default
    # visibility and exports everything; if hidden visibility is turned on, the
    # bindings' referenced symbols must carry EINSUMS_EXPORT.
    target_link_libraries(PyEinsums PRIVATE Einsums)
    # ``einsums_private_flags`` carries project-wide compile-time switches the
    # per-module targets pick up via einsums_add_module. pybind11_add_module
    # creates a fresh target that does NOT link against it transitively, so
    # without this PyEinsums compiles with raw conda flags and trips warnings
    # our private-flags target was set up to silence — most visibly the GCC
    # ``-Winterference-size`` from Profile/RingBuffer.hpp's use of
    # ``std::hardware_destructive_interference_size``. Adding it here mirrors
    # what einsums_add_executable does for ordinary in-tree targets.
    if(TARGET einsums_private_flags)
        target_link_libraries(PyEinsums PRIVATE einsums_private_flags)
    endif()

    list(LENGTH _modules _count)
    message(STATUS "apiary: PyEinsums aggregates ${_count} module(s): ${_modules}")

    # Wire pseudo-targets registered by einsums_add_python_unit_test() to
    # depend on PyEinsums. The function can't do this itself because it runs
    # before the PyEinsums target exists.
    get_property(_pyt_targets GLOBAL PROPERTY EINSUMS_PYTHON_UNIT_TEST_TARGETS)
    foreach(_pyt_target IN LISTS _pyt_targets)
        add_dependencies("${_pyt_target}" PyEinsums)
    endforeach()
endfunction()
