#----------------------------------------------------------------------------------------------
# Copyright (c) The Einsums Developers. All rights reserved.
# Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#----------------------------------------------------------------------------------------------

# einsums_finalize_pybind() — assemble the autogenerated bindings from
# every module that opted into ``einsums_add_module(... PYBIND ...)``
# into a single ``PyEinsums`` Python extension that exposes them all
# under one ``import einsums`` call.
#
# Must run AFTER ``add_subdirectory(libs)`` because each annotated
# module appends to GLOBAL properties:
#
#     EINSUMS_PYBIND_MODULES                 — list of module names
#     EINSUMS_PYBIND_LINK_TARGETS            — list of einsums library targets
#     EINSUMS_PYBIND_HEADERS_<MODULE>        — absolute header paths
#     EINSUMS_PYBIND_RELHEADERS_<MODULE>     — relative-to-HEADER_ROOT names
#     EINSUMS_PYBIND_INCFLAGS_<MODULE>       — module-specific -I flags
#     EINSUMS_PYBIND_LIBNAME_<MODULE>        — owning library name (Einsums)
#
# Per-module ``add_custom_command(OUTPUT)`` calls are emitted here at
# root scope so the consuming ``target_sources(PyEinsums PRIVATE ...)``
# stays in the same directory — CMake silently drops cross-scope
# custom-command outputs from a target's source list otherwise.


function(einsums_finalize_pybind)
    if(NOT EINSUMS_BUILD_PYTHON)
        return()
    endif()

    get_property(_modules GLOBAL PROPERTY EINSUMS_PYBIND_MODULES)
    get_property(_targets GLOBAL PROPERTY EINSUMS_PYBIND_LINK_TARGETS)

    if(NOT _modules)
        message(STATUS "apiary: no modules opted in via PYBIND — skipping aggregator.")
        return()
    endif()


    # Configure-time-generated Defines.hpp files. Adding them to every
    # codegen edge's DEPENDS makes the codegen re-fire when configure
    # toggles a flag (EINSUMS_WITH_GPU=ON, ...) — the regenerated
    # Defines.hpp changes mtime, so any annotated header that uses
    # ``#if defined(EINSUMS_HAVE_GPU)`` produces fresh output. Each
    # module writes its own ``${BUILD}/libs/<Lib>/<Mod>/include/<Lib>/<Mod>/Defines.hpp``
    # via einsums_write_config_defines_file, so a recursive glob picks
    # them all up.
    file(GLOB_RECURSE _all_defines_headers
        "${PROJECT_BINARY_DIR}/libs/*/Defines.hpp"
    )

    # Emit one add_custom_command per opted-in module producing its
    # generated TU.
    set(_generated_tus "")
    set(_docs_jsons "")
    foreach(_mod IN LISTS _modules)
        get_property(_headers      GLOBAL PROPERTY EINSUMS_PYBIND_HEADERS_${_mod})
        get_property(_relheaders   GLOBAL PROPERTY EINSUMS_PYBIND_RELHEADERS_${_mod})
        get_property(_deps         GLOBAL PROPERTY EINSUMS_PYBIND_DEPS_${_mod})
        get_property(_header_root  GLOBAL PROPERTY EINSUMS_PYBIND_HEADER_ROOT_${_mod})
        get_property(_bin_inc      GLOBAL PROPERTY EINSUMS_PYBIND_BIN_INC_${_mod})
        get_property(_libname      GLOBAL PROPERTY EINSUMS_PYBIND_LIBNAME_${_mod})

        # apiary_add_bindings populates these via OUT_* (PARENT_SCOPE);
        # pre-declare so the static cmake-audit check sees them defined.
        set(_out "")
        set(_stub_out "")
        set(_docs_json "")
        apiary_add_bindings(
            BINDING DOCS_JSON
            HEADERS ${_headers}
            SOURCE_INCLUDES ${_relheaders}
            REGISTER_FUNCTION apiary_register_${_mod}
            MODULE einsums
            DEPENDS_TARGETS ${_deps}
            OUTPUT_DIR "${CMAKE_BINARY_DIR}/generated/pybind"
            OUTPUT_NAME "${_libname}_${_mod}"
            CXX_STANDARD ${EINSUMS_WITH_CXX_STANDARD}
            # Module-local include roots not carried by the dependency targets'
            # usage requirements: the module's own source + build include dirs,
            # the build root (Config.hpp), the annotations shim, and apiary's
            # own headers.
            EXTRA_FLAGS
                "-I${_header_root}"
                "-I${_bin_inc}"
                "-I${CMAKE_BINARY_DIR}"
                "-I${CMAKE_SOURCE_DIR}/libs/Einsums/Python/include"
                "-I${CMAKE_SOURCE_DIR}/external/apiary/include"
            EXTRA_DEPENDS ${_all_defines_headers}
            OUT_BINDING _out OUT_STUB _stub_out OUT_DOCS_JSON _docs_json
        )
        list(APPEND _generated_tus   "${_out}")
        list(APPEND _generated_stubs "${_stub_out}")
        list(APPEND _docs_jsons      "${_docs_json}")
    endforeach()

    # Generate the tiny per-module list header consumed by the static
    # ``PyEinsumsMain.cpp`` aggregator. This is the only piece that varies
    # with the enabled-module set; everything else (init, atexit,
    # PYBIND11_MODULE body) lives in checked-in C++ source.
    set(_prototypes "")
    set(_calls "")
    foreach(_mod IN LISTS _modules)
        set(_prototypes "${_prototypes}void apiary_register_${_mod}(::pybind11::module_ &m);\n")
        set(_calls      "${_calls}    apiary_register_${_mod}(m);\n")
    endforeach()

    set(_modules_hdr_dir "${CMAKE_BINARY_DIR}/generated/pybind/include/Einsums/Python/Detail")
    set(_modules_hdr     "${_modules_hdr_dir}/PyEinsumsModules.hpp")
    file(MAKE_DIRECTORY "${_modules_hdr_dir}")
    file(WRITE "${_modules_hdr}"
"// This file is generated by einsums_finalize_pybind. Do not edit.\n"
"//\n"
"// Per-module register function declarations and the inline aggregator\n"
"// called from PyEinsumsMain.cpp's PYBIND11_MODULE body. The list of\n"
"// modules tracks which Einsums libraries opted in via\n"
"// einsums_add_module(... PYBIND ON).\n"
"\n"
"#pragma once\n"
"\n"
"#include <pybind11/pybind11.h>\n"
"\n"
"${_prototypes}"
"\n"
"inline void apiary_register_all(::pybind11::module_ &m) {\n"
"${_calls}"
"}\n"
    )

    set(_main_cpp "${CMAKE_SOURCE_DIR}/libs/Einsums/Python/src/PyEinsumsMain.cpp")
    pybind11_add_module(PyEinsums "${_main_cpp}" ${_generated_tus})
    set_target_properties(PyEinsums PROPERTIES OUTPUT_NAME _core)
    # The static main needs to find the autogenerated modules header.
    target_include_directories(PyEinsums PRIVATE "${CMAKE_BINARY_DIR}/generated/pybind/include")

    # Land the compiled extension and the Python shell files together as
    # a proper package: ``${CMAKE_BINARY_DIR}/lib/einsums/{_core.so,
    # __init__.py, rc.py}``. The .py files are checked-in static sources
    # under libs/Einsums/Python/python/einsums/ and copied verbatim.
    set(_pkg_dir "${CMAKE_BINARY_DIR}/lib/einsums")
    set_target_properties(PyEinsums PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${_pkg_dir}")
    set(_pkg_src "${CMAKE_SOURCE_DIR}/libs/Einsums/Python/python/einsums")
    file(MAKE_DIRECTORY "${_pkg_dir}")
    # configure_file(... COPYONLY) tracks the source mtime as a configure-time
    # dependency: editing any of these files triggers an automatic re-configure
    # on the next build, so the package's runtime copy never goes stale. (The
    # earlier ``file(COPY)`` ran once and required a manual ``cmake -B build``
    # to pick up edits.)
    configure_file("${_pkg_src}/__init__.py" "${_pkg_dir}/__init__.py" COPYONLY)
    configure_file("${_pkg_src}/rc.py"       "${_pkg_dir}/rc.py"       COPYONLY)
    configure_file("${_pkg_src}/graph.py"    "${_pkg_dir}/graph.py"    COPYONLY)
    configure_file("${_pkg_src}/profile.py"  "${_pkg_dir}/profile.py"  COPYONLY)
    # einsums.testing — pure-Python sub-package of test helpers.
    file(MAKE_DIRECTORY "${_pkg_dir}/testing")
    configure_file("${_pkg_src}/testing/__init__.py"
                   "${_pkg_dir}/testing/__init__.py" COPYONLY)

    # Aggregate per-module .pyi fragments into per-submodule stub files
    # (einsums/_core.pyi, einsums/<sub>.pyi) plus the PEP-561 ``py.typed``
    # marker. The stamp file is what the custom target depends on; touch
    # it whenever any fragment changes.
    set(_stubs_stamp "${CMAKE_BINARY_DIR}/generated/pybind/.stubs.stamp")
    set(_aggregator  "${CMAKE_SOURCE_DIR}/external/apiary/scripts/aggregate_stubs.py")
    # Collect the hand-written .py helpers so editing them re-runs the
    # aggregator (which merges their public surface into the matching
    # <sub>.pyi for pyright). Both top-level files (graph.py, rc.py) and
    # pure-Python helper sub-packages (testing/__init__.py) are tracked
    # so __init__.pyi's submodule re-exports stay in sync.
    file(GLOB _py_helpers      CONFIGURE_DEPENDS "${_pkg_src}/*.py")
    file(GLOB _py_helper_pkgs  CONFIGURE_DEPENDS "${_pkg_src}/*/__init__.py")
    add_custom_command(
        OUTPUT ${_stubs_stamp}
        COMMAND ${Python_EXECUTABLE} ${_aggregator}
                --frag-dir       "${CMAKE_BINARY_DIR}/generated/pybind"
                --pkg-dir        "${_pkg_dir}"
                --py-helpers-dir "${_pkg_src}"
        COMMAND ${CMAKE_COMMAND} -E touch ${_stubs_stamp}
        DEPENDS ${_aggregator} ${_generated_stubs} ${_py_helpers} ${_py_helper_pkgs}
        COMMENT "apiary: aggregating .pyi stubs into ${_pkg_dir}"
        VERBATIM
    )
    add_custom_target(PyEinsumsStubs ALL DEPENDS ${_stubs_stamp})
    add_dependencies(PyEinsumsStubs PyEinsums)

    # Render the per-module docs JSON into a Sphinx Python API reference,
    # grouped by submodule. Deliberately NOT part of ALL — it is built on
    # demand (``cmake --build . --target PyEinsumsDocs``) and is wired as a
    # dependency of the documentation build when EINSUMS_WITH_DOCUMENTATION
    # is on. Pages land in ${_docs_out_dir}; the docs tree pulls them in.
    set(_docs_out_dir  "${CMAKE_BINARY_DIR}/generated/pybind/docs")
    set(_docs_stamp    "${CMAKE_BINARY_DIR}/generated/pybind/.docs.stamp")
    set(_docs_renderer "${CMAKE_SOURCE_DIR}/external/apiary/scripts/render_docs_rst.py")
    add_custom_command(
        OUTPUT ${_docs_stamp}
        COMMAND ${CMAKE_COMMAND} -E make_directory "${_docs_out_dir}"
        COMMAND ${Python_EXECUTABLE} ${_docs_renderer}
                --outdir "${_docs_out_dir}" ${_docs_jsons}
        COMMAND ${CMAKE_COMMAND} -E touch ${_docs_stamp}
        DEPENDS ${_docs_renderer} ${_docs_jsons}
        COMMENT "apiary: rendering Python API reference (.rst) into ${_docs_out_dir}"
        VERBATIM
    )
    add_custom_target(PyEinsumsDocs DEPENDS ${_docs_stamp})
    # Link ONLY the umbrella ``Einsums`` shared library. Linking the per-module
    # targets (${_targets}) as well baked each module's object files into _core.so
    # on top of libEinsums.dylib, duplicating code/RTTI. Everything _core needs is
    # in libEinsums.dylib, so we rely on it alone — any symbol the bindings
    # reference must therefore be exported by libEinsums (EINSUMS_EXPORT). With
    # EINSUMS_WITH_HIDDEN_VISIBILITY off (the Apple/Clang default) it has default
    # visibility and exports everything; if hidden visibility is turned on, the
    # bindings' referenced symbols must carry EINSUMS_EXPORT.
    target_link_libraries(PyEinsums PRIVATE Einsums)
    # ``einsums_private_flags`` carries project-wide compile-time switches the
    # per-module targets pick up via einsums_add_module. pybind11_add_module
    # creates a fresh target that does NOT link against it transitively, so
    # without this PyEinsums compiles with raw conda flags and trips warnings
    # our private-flags target was set up to silence — most visibly the GCC
    # ``-Winterference-size`` from Profile/RingBuffer.hpp's use of
    # ``std::hardware_destructive_interference_size``. Adding it here mirrors
    # what einsums_add_executable does for ordinary in-tree targets.
    if(TARGET einsums_private_flags)
        target_link_libraries(PyEinsums PRIVATE einsums_private_flags)
    endif()

    list(LENGTH _modules _count)
    message(STATUS "apiary: PyEinsums aggregates ${_count} module(s): ${_modules}")

    # Wire pseudo-targets registered by einsums_add_python_unit_test() to
    # depend on PyEinsums. The function can't do this itself because it runs
    # before the PyEinsums target exists.
    get_property(_pyt_targets GLOBAL PROPERTY EINSUMS_PYTHON_UNIT_TEST_TARGETS)
    foreach(_pyt_target IN LISTS _pyt_targets)
        add_dependencies("${_pyt_target}" PyEinsums)
    endforeach()
endfunction()
