//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from dlpno.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: aa134ad024e8ec78c3e29a468f3ff42b

/// @file
/// The dlpno stage module: the handshake, and one entry point per stage.

#include <Einsums/Python/StageModule.hpp>

#include <dlpno/Casters.hpp>
#include <dlpno/ComputePnoOverlaps.hpp>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

PYBIND11_MODULE(dlpno_stages, m) {
    m.doc() = "C++ backends for the dlpno stages.";

    // Must come first: einsums.stages.load_stage_module refuses to read
    // anything out of a module that has not registered against the same
    // libEinsums it is bound to.
    EINSUMS_STAGE_MODULE(m, "dlpno_stages");

    // Returned contracts are real bound types. Argument-position contracts
    // cross through the casters in Casters.hpp instead, which is why they need
    // no class_ here: direction decides the mechanism.
    py::class_<dlpno::PnoOverlaps>(m, "PnoOverlaps")
        .def_readonly("S_cls", &dlpno::PnoOverlaps::S_cls)
        .def_readonly("S_T", &dlpno::PnoOverlaps::S_T);

    // The stage_ prefix is what load_stage_module scans for: the module states
    // which of its symbols are stages rather than leaving the loader to guess
    // from everything callable.
    m.def("stage_compute_pno_overlaps", &dlpno::compute_pno_overlaps, py::arg("X_pno"), py::arg("S_pao"), py::arg("lmopair_to_paos"),
          py::arg("n_pno"), py::arg("bucket_of"), py::arg("bucket_dims"), py::arg("plan"),
          "Overlaps between every coupled pair of PNO bases, scaled by the Fock element.");
}
