//----------------------------------------------------------------------------------------------
// Copyright (c) The Einsums Developers. All rights reserved.
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.
//----------------------------------------------------------------------------------------------

// Generated by 'python -m einsums.stages promote' from dlpno.stages.
// Edits are lost on the next run; change the Python contract instead.
// promote-hash: 413026de751e1cc7524544fb66917f10

/// @file
/// The dlpno stage module: the handshake, and one entry point per stage.

#include <Einsums/Python/StageModule.hpp>

#include <dlpno/Casters.hpp>
#include <dlpno/ComputePnoOverlaps.hpp>
#include <dlpno/TransformPnos.hpp>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

PYBIND11_MODULE(dlpno_stages, m) {
    m.doc() = "C++ backends for the dlpno stages.";

    // Must come first: einsums.stages.load_stage_module refuses to read
    // anything out of a module that has not registered against the same
    // libEinsums it is bound to.
    EINSUMS_STAGE_MODULE(m, "dlpno_stages");

    // Returned contracts are real bound types. Argument-position contracts
    // cross through the casters in Casters.hpp instead, which is why they need
    // no class_ here: direction decides the mechanism.
    // Every access to a list-valued field converts the underlying
    // std::vector into a fresh Python list. A consumer that indexes
    // result.field[i] inside a loop is therefore quadratic in the list
    // length; read each field into a local once and index that.
    py::class_<dlpno::PnoOverlaps>(m, "PnoOverlaps")
        .def_readonly("S_cls", &dlpno::PnoOverlaps::S_cls)
        .def_readonly("S_T", &dlpno::PnoOverlaps::S_T);
    // Every access to a list-valued field converts the underlying
    // std::vector into a fresh Python list. A consumer that indexes
    // result.field[i] inside a loop is therefore quadratic in the list
    // length; read each field into a local once and index that.
    py::class_<dlpno::PnoTransform>(m, "PnoTransform")
        .def_readonly("K_pno", &dlpno::PnoTransform::K_pno)
        .def_readonly("T_pno", &dlpno::PnoTransform::T_pno)
        .def_readonly("X_pno", &dlpno::PnoTransform::X_pno)
        .def_readonly("e_pno", &dlpno::PnoTransform::e_pno)
        .def_readonly("n_pno", &dlpno::PnoTransform::n_pno)
        .def_readonly("e_initial", &dlpno::PnoTransform::e_initial)
        .def_readonly("e_os_initial", &dlpno::PnoTransform::e_os_initial)
        .def_readonly("e_trunc", &dlpno::PnoTransform::e_trunc)
        .def_readonly("e_os_trunc", &dlpno::PnoTransform::e_os_trunc);

    // The stage_ prefix is what load_stage_module scans for: the module states
    // which of its symbols are stages rather than leaving the loader to guess
    // from everything callable.
    m.def("stage_compute_pno_overlaps", &dlpno::compute_pno_overlaps, py::arg("X_pno"), py::arg("S_pao"), py::arg("lmopair_to_paos"),
          py::arg("n_pno"), py::arg("bucket_of"), py::arg("bucket_dims"), py::arg("plan"),
          "Overlaps between every coupled pair of PNO bases, scaled by the Fock element.");
    m.def("stage_transform_pnos", &dlpno::transform_pnos, py::arg("q_ia"), py::arg("fits"), py::arg("fit_of"), py::arg("fit_pos"),
          py::arg("dom_X"), py::arg("dom_e"), py::arg("dom_F"), py::arg("dom_of"), py::arg("ribfs"), py::arg("paos"), py::arg("lmo_j"),
          py::arg("shift"), py::arg("pno_scale"), py::arg("min_pnos"), py::arg("t_cut_pno"),
          "Build each upper pair's truncated, canonical PNO basis.");
}
