name: Identify changed files

on:
  workflow_call:
    outputs:
      filters:
        description: Matched filters
        value: ${{ jobs.need_check.outputs.filters }}

permissions: read-all

jobs:
  need_check:
    name: Find
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      filters: ${{ steps.result.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Check file changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'libs/**/*.hpp'
              - 'libs/**/*.h'
              - '.github/workflows/docs.yml'
            ci:
              - '.github/workflows/**'
            src:
              - 'cmake/**'
              - 'libs/**'
              - 'testing/**'
            cmake:
              - 'CMakeLists.txt'
              - '**/CMakeLists.txt'
              - '**/*.cmake'
              - '.cmake-format.py'
            cpp:
              - '**/*.cpp'
              - '**/*.c'
              - '**/*.hpp'
              - '**/*.h'
              - '.clang-format'

      - name: Set output
        id: result
        uses: actions/github-script@v9
        with:
          script: |
            return '${{ steps.changes.outputs.changes }}';

      - run: echo '${{ steps.result.outputs.result }}'
